#nullable enable
#pragma warning disable CS1591

// <auto-generated />

using System.Collections.ObjectModel;
using System.Text.Json.Serialization;

namespace Harborline.Contracts.Authorization;

public static class RoleVocabularies
{
    public const string Platform = "sys.platform-roles";
    public const string Domain = "tax.roles";
}

public sealed record RoleReference(
    [property: JsonPropertyName("vocabulary")] string Vocabulary,
    [property: JsonPropertyName("name")] string Name)
{
    public static RoleReference Administrator { get; } = new(RoleVocabularies.Platform, "administrator");
    public static RoleReference Auditor { get; } = new(RoleVocabularies.Platform, "auditor");
    public static RoleReference Domain(string name) => new(RoleVocabularies.Domain, name);
}

[JsonConverter(typeof(JsonStringEnumConverter<RoleOwnerKind>))]
public enum RoleOwnerKind { Platform, Package, Tenant }

public sealed record RoleOwner(
    [property: JsonPropertyName("kind")] RoleOwnerKind Kind,
    [property: JsonPropertyName("ownerId")] string OwnerId);

public sealed record RoleDefinition(
    [property: JsonPropertyName("roleDefinitionId")] Guid RoleDefinitionId,
    [property: JsonPropertyName("role")] RoleReference Role,
    [property: JsonPropertyName("displayName")] string DisplayName,
    [property: JsonPropertyName("owner")] RoleOwner Owner,
    [property: JsonPropertyName("isSealed")] bool IsSealed);

public sealed record RoleGate(
    [property: JsonPropertyName("requiredRoles")] IReadOnlyList<RoleReference> RequiredRoles);

public sealed record HeldRoleSet(
    [property: JsonPropertyName("roles")] IReadOnlyList<RoleReference> Roles);

public sealed record RecordStandingReference(
    [property: JsonPropertyName("name")] string Name);

public static class PlatformRoleVocabulary
{
    private static readonly IReadOnlyCollection<RoleReference> DefinedRoles =
        new ReadOnlyCollection<RoleReference>([RoleReference.Administrator, RoleReference.Auditor]);

    public static IReadOnlyCollection<RoleReference> Roles => DefinedRoles;
    public static bool Contains(RoleReference role) => DefinedRoles.Contains(role);
}

public sealed class RoleVocabulary
{
    private readonly IReadOnlyDictionary<RoleReference, RoleDefinition> _definitions;

    private RoleVocabulary(IReadOnlyDictionary<RoleReference, RoleDefinition> definitions) =>
        _definitions = definitions;

    public static RoleVocabulary FromApi(IEnumerable<RoleDefinition> definitions)
    {
        ArgumentNullException.ThrowIfNull(definitions);
        var snapshot = new Dictionary<RoleReference, RoleDefinition>();
        foreach (var definition in definitions)
        {
            ArgumentNullException.ThrowIfNull(definition);
            ValidateReference(definition.Role);
            var platformVocabulary = definition.Role.Vocabulary == RoleVocabularies.Platform;
            var platformOwner = definition.Owner.Kind == RoleOwnerKind.Platform;
            if (platformVocabulary != platformOwner || definition.IsSealed != platformOwner)
                throw new ArgumentException("invalid-role-ownership", nameof(definitions));
            if (platformOwner && !PlatformRoleVocabulary.Contains(definition.Role))
                throw new ArgumentException("invalid-platform-role", nameof(definitions));
            if (definition.RoleDefinitionId == Guid.Empty
                || string.IsNullOrWhiteSpace(definition.DisplayName)
                || string.IsNullOrWhiteSpace(definition.Owner.OwnerId))
                throw new ArgumentException("invalid-role-definition", nameof(definitions));
            if (!snapshot.TryAdd(definition.Role, definition))
                throw new ArgumentException("duplicate-role-reference", nameof(definitions));
        }
        return new RoleVocabulary(new ReadOnlyDictionary<RoleReference, RoleDefinition>(snapshot));
    }

    public RoleDefinition? Resolve(RoleReference role)
    {
        ValidateReference(role);
        return _definitions.GetValueOrDefault(role);
    }

    public RoleDefinition Require(RoleReference role) =>
        Resolve(role) ?? throw new KeyNotFoundException("unknown-role-reference");

    private static void ValidateReference(RoleReference role)
    {
        ArgumentNullException.ThrowIfNull(role);
        if (role.Vocabulary is not RoleVocabularies.Platform and not RoleVocabularies.Domain)
            throw new ArgumentException("unknown-role-vocabulary", nameof(role));
        if (string.IsNullOrWhiteSpace(role.Name))
            throw new ArgumentException("invalid-role-reference", nameof(role));
    }
}

public static class RoleGateResolver
{
    public static bool Allows(RoleGate gate, RoleVocabulary vocabulary, HeldRoleSet heldRoles)
    {
        ArgumentNullException.ThrowIfNull(gate);
        ArgumentNullException.ThrowIfNull(vocabulary);
        ArgumentNullException.ThrowIfNull(heldRoles);
        if (gate.RequiredRoles.Count == 0) return true;
        try
        {
            if (gate.RequiredRoles.Any(role => vocabulary.Resolve(role) is null)) return false;
        }
        catch (ArgumentException)
        {
            return false;
        }
        var held = heldRoles.Roles.ToHashSet();
        return gate.RequiredRoles.Any(held.Contains);
    }
}
