import type {Meta,StoryObj} from '@storybook/react-vite'
import {ConversationList,type ConversationSummary} from '@harborline-software/ui-react'
type Id='conversation-list.empty'|'conversation-list.rows'|'conversation-list.rename'|'conversation-list.delete'|'conversation-list.locale-ar'|'conversation-list.invalid'|'conversation-list.theme-light'|'conversation-list.theme-dark'|'conversation-list.content'
const rows:ConversationSummary[]=[{id:'c1',title:'Blueprint review',timestamp:'2 min ago',preview:'Placement confirmed in bay 4.'},{id:'c2',title:'Inspection notes',timestamp:'Yesterday',preview:'Three photos need review.'}]
const contentRows:ConversationSummary[]=[{id:'c1',title:'Awaiting third-party structural certification review',timestamp:'1,284,905 records',preview:'Bay 4 <grid C-7> & 8'},{id:'c2',title:'Ordnance Survey — Niño Ångström',timestamp:'Yesterday'}]
function Scene({scenarioId}:{scenarioId:Id}){const rtl=scenarioId==='conversation-list.locale-ar';const dark=scenarioId==='conversation-list.theme-dark';const empty=scenarioId==='conversation-list.empty';return <section className="hl-gallery-scene" data-gallery-probe data-gallery-scenario={scenarioId} data-theme={dark?'dark':undefined} dir={rtl?'rtl':undefined}><div className="hl-gallery-stage" style={{minHeight:280}}>{scenarioId==='conversation-list.content'?<ConversationList conversations={contentRows} activeId="c1" onSelect={()=>{}} onNew={()=>{}} onRename={()=>{}} onDelete={()=>{}}/>:<ConversationList conversations={empty?[]:rows} activeId="c1" onSelect={()=>{}} onNew={()=>{}} onRename={()=>{}} onDelete={()=>{}} labels={rtl?{heading:'المحادثات',newConversation:'محادثة جديدة',empty:'لا توجد محادثات'}:undefined}/>}</div></section>}
const meta={title:'Platform/Conversation List',component:Scene,parameters:{layout:'padded',controls:{disable:true}}} satisfies Meta<typeof Scene>;export default meta;type Story=StoryObj<typeof meta>
export const Empty:Story={name:'Empty state',args:{scenarioId:'conversation-list.empty'}};export const Rows:Story={name:'Rows and active state',args:{scenarioId:'conversation-list.rows'}};export const Rename:Story={name:'Rename workflow',args:{scenarioId:'conversation-list.rename'}};export const Delete:Story={name:'Confirmed delete workflow',args:{scenarioId:'conversation-list.delete'}};export const Arabic:Story={name:'Arabic and expanded labels',args:{scenarioId:'conversation-list.locale-ar'}};export const Invalid:Story={name:'Input validation',args:{scenarioId:'conversation-list.invalid'}};export const Light:Story={name:'Light theme',args:{scenarioId:'conversation-list.theme-light'}};export const Dark:Story={name:'Dark theme',args:{scenarioId:'conversation-list.theme-dark'}}
;export const Content:Story={name:'Content resilience',args:{scenarioId:'conversation-list.content'}}
