#nullable enable
#pragma warning disable CS1591 // Generated public wire surface is documented by the frozen TypeScript contract.

// <auto-generated />
using System.Text.Json;
using System.Text.Json.Serialization;
using Harborline.Contracts.Authorization;

namespace Harborline.Contracts.Forms;

public sealed record InternationalizedText
{
    [JsonPropertyName("defaultLocale")]
    [JsonRequired]
    public required string DefaultLocale { get; init; }

    [JsonPropertyName("values")]
    [JsonRequired]
    public required IReadOnlyDictionary<string, string> Values { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<FormDefinitionStatus>))]
public enum FormDefinitionStatus
{
    [JsonStringEnumMemberName("Draft")]
    Draft,
    [JsonStringEnumMemberName("Published")]
    Published,
    [JsonStringEnumMemberName("Deprecated")]
    Deprecated,
    [JsonStringEnumMemberName("Withdrawn")]
    Withdrawn,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<PiiSensitivity>))]
public enum PiiSensitivity
{
    [JsonStringEnumMemberName("None")]
    None,
    [JsonStringEnumMemberName("Sensitive")]
    Sensitive,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<RuleTier>))]
public enum RuleTier
{
    [JsonStringEnumMemberName("JsonSchema")]
    JsonSchema,
    [JsonStringEnumMemberName("JsonLogic")]
    JsonLogic,
    [JsonStringEnumMemberName("PowerFx")]
    PowerFx,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<RuleScope>))]
public enum RuleScope
{
    [JsonStringEnumMemberName("Field")]
    Field,
    [JsonStringEnumMemberName("Section")]
    Section,
    [JsonStringEnumMemberName("Schema")]
    Schema,
    [JsonStringEnumMemberName("Row")]
    Row,
    [JsonStringEnumMemberName("Table")]
    Table,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<RuleActionKind>))]
public enum RuleActionKind
{
    [JsonStringEnumMemberName("Visibility")]
    Visibility,
    [JsonStringEnumMemberName("Required")]
    Required,
    [JsonStringEnumMemberName("ReadOnly")]
    ReadOnly,
    [JsonStringEnumMemberName("Validate")]
    Validate,
    [JsonStringEnumMemberName("Compute")]
    Compute,
    [JsonStringEnumMemberName("Presentation")]
    Presentation,
    [JsonStringEnumMemberName("Options")]
    Options,
}

public sealed record PresentationHint
{
    [JsonPropertyName("severity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PresentationHintSeverityValue> Severity { get; init; }

    [JsonPropertyName("badge")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Badge { get; init; }

    [JsonPropertyName("styleToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> StyleToken { get; init; }

}

[JsonConverter(typeof(ControlHintJsonConverter))]
public readonly record struct ControlHint(string Value)
{
    public static implicit operator ControlHint(string value) => new(value);
    public static implicit operator string(ControlHint value) => value.Value;
    public override string ToString() => Value;
}

[JsonConverter(typeof(ClosedEnumJsonConverter<SectionLayoutKind>))]
public enum SectionLayoutKind
{
    [JsonStringEnumMemberName("stack")]
    Stack,
    [JsonStringEnumMemberName("flex")]
    Flex,
    [JsonStringEnumMemberName("grid")]
    Grid,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<FlexDirection>))]
public enum FlexDirection
{
    [JsonStringEnumMemberName("row")]
    Row,
    [JsonStringEnumMemberName("column")]
    Column,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<FlexWrap>))]
public enum FlexWrap
{
    [JsonStringEnumMemberName("nowrap")]
    Nowrap,
    [JsonStringEnumMemberName("wrap")]
    Wrap,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<LayoutBreakpoint>))]
public enum LayoutBreakpoint
{
    [JsonStringEnumMemberName("sm")]
    Sm,
    [JsonStringEnumMemberName("md")]
    Md,
    [JsonStringEnumMemberName("lg")]
    Lg,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<LayoutDensity>))]
public enum LayoutDensity
{
    [JsonStringEnumMemberName("comfortable")]
    Comfortable,
    [JsonStringEnumMemberName("compact")]
    Compact,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<LayoutAlign>))]
public enum LayoutAlign
{
    [JsonStringEnumMemberName("start")]
    Start,
    [JsonStringEnumMemberName("center")]
    Center,
    [JsonStringEnumMemberName("end")]
    End,
    [JsonStringEnumMemberName("stretch")]
    Stretch,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<FieldWidth>))]
public enum FieldWidth
{
    [JsonStringEnumMemberName("auto")]
    Auto,
    [JsonStringEnumMemberName("1/4")]
    OneQuarter,
    [JsonStringEnumMemberName("1/3")]
    OneThird,
    [JsonStringEnumMemberName("1/2")]
    OneHalf,
    [JsonStringEnumMemberName("2/3")]
    TwoThirds,
    [JsonStringEnumMemberName("3/4")]
    ThreeQuarters,
    [JsonStringEnumMemberName("full")]
    Full,
}

public sealed record SectionLayout
{
    [JsonPropertyName("kind")]
    [JsonRequired]
    public required SectionLayoutKind Kind { get; init; }

    [JsonPropertyName("direction")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FlexDirection> Direction { get; init; }

    [JsonPropertyName("wrap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FlexWrap> Wrap { get; init; }

    [JsonPropertyName("columns")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal> Columns { get; init; }

    [JsonPropertyName("gap")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutGap> Gap { get; init; }

    [JsonPropertyName("collapseBelow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutBreakpoint> CollapseBelow { get; init; }

    [JsonPropertyName("density")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutDensity> Density { get; init; }

    [JsonPropertyName("align")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutAlign> Align { get; init; }

}

public sealed record FieldPlacement
{
    [JsonPropertyName("colSpan")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal> ColSpan { get; init; }

    [JsonPropertyName("grow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal> Grow { get; init; }

    [JsonPropertyName("width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FieldWidth> Width { get; init; }

    [JsonPropertyName("align")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutAlign> Align { get; init; }

}

public sealed record SectionAccess
{
    [JsonPropertyName("readRoles")]
    [JsonRequired]
    public required IReadOnlyList<RoleReference> ReadRoles { get; init; }

    [JsonPropertyName("writeRoles")]
    [JsonRequired]
    public required IReadOnlyList<RoleReference> WriteRoles { get; init; }

    [JsonPropertyName("readConditionExpression")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> ReadConditionExpression { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<FormItemKind>))]
public enum FormItemKind
{
    [JsonStringEnumMemberName("field")]
    Field,
    [JsonStringEnumMemberName("group")]
    Group,
    [JsonStringEnumMemberName("collection")]
    Collection,
    [JsonStringEnumMemberName("reference")]
    Reference,
    [JsonStringEnumMemberName("content")]
    Content,
    [JsonStringEnumMemberName("action")]
    Action,
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(HeadingContentNode), typeDiscriminator: "heading")]
[JsonDerivedType(typeof(ParagraphContentNode), typeDiscriminator: "paragraph")]
public abstract record ContentNode;

public sealed record HeadingContentNode : ContentNode
{
    [JsonPropertyName("text")]
    [JsonRequired]
    public required InternationalizedText Text { get; init; }

    [JsonPropertyName("level")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal> Level { get; init; }

}

public sealed record ParagraphContentNode : ContentNode
{
    [JsonPropertyName("text")]
    [JsonRequired]
    public required InternationalizedText Text { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<FormActionKind>))]
public enum FormActionKind
{
    [JsonStringEnumMemberName("open-url")]
    OpenUrl,
    [JsonStringEnumMemberName("scroll-to-section")]
    ScrollToSection,
}

public sealed record FormActionConfig
{
    [JsonPropertyName("kind")]
    [JsonRequired]
    public required FormActionKind Kind { get; init; }

    [JsonPropertyName("label")]
    [JsonRequired]
    public required InternationalizedText Label { get; init; }

    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Url { get; init; }

    [JsonPropertyName("sectionId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> SectionId { get; init; }

}

public sealed record ReusableUnitVersionSelector
{
    [JsonPropertyName("pinnedVersion")]
    [JsonRequired]
    public required string? PinnedVersion { get; init; }

}

public sealed record ReusableUnitRef
{
    [JsonPropertyName("unitId")]
    [JsonRequired]
    public required string UnitId { get; init; }

    [JsonPropertyName("version")]
    [JsonRequired]
    public required ReusableUnitVersionSelector Version { get; init; }

}

public sealed record Cardinality
{
    [JsonPropertyName("min")]
    [JsonRequired]
    public required decimal Min { get; init; }

    [JsonPropertyName("max")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal?> Max { get; init; }

}

public sealed record CollectionColumn
{
    [JsonPropertyName("width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FieldWidth> Width { get; init; }

    [JsonPropertyName("align")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LayoutAlign> Align { get; init; }

}

public sealed record CollectionTableConfig
{
    [JsonPropertyName("columns")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, CollectionColumn>> Columns { get; init; }

    [JsonPropertyName("totals")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<string>> Totals { get; init; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(FieldFormItem), typeDiscriminator: "field")]
[JsonDerivedType(typeof(GroupFormItem), typeDiscriminator: "group")]
[JsonDerivedType(typeof(CollectionFormItem), typeDiscriminator: "collection")]
[JsonDerivedType(typeof(ReferenceFormItem), typeDiscriminator: "reference")]
[JsonDerivedType(typeof(ContentFormItem), typeDiscriminator: "content")]
[JsonDerivedType(typeof(ActionFormItem), typeDiscriminator: "action")]
public abstract record FormItem;

public sealed record FieldFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

}

public sealed record GroupFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Title { get; init; }

    [JsonPropertyName("items")]
    [JsonRequired]
    public required IReadOnlyList<FormItem> Items { get; init; }

    [JsonPropertyName("layout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SectionLayout> Layout { get; init; }

    [JsonPropertyName("placement")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, FieldPlacement>> Placement { get; init; }

    [JsonPropertyName("aspects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AspectOverlay> Aspects { get; init; }

}

public sealed record CollectionFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Title { get; init; }

    [JsonPropertyName("items")]
    [JsonRequired]
    public required IReadOnlyList<FormItem> Items { get; init; }

    [JsonPropertyName("cardinality")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Cardinality> Cardinality { get; init; }

    [JsonPropertyName("table")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<CollectionTableConfig> Table { get; init; }

    [JsonPropertyName("aspects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AspectOverlay> Aspects { get; init; }

}

public sealed record ReferenceFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("reference")]
    [JsonRequired]
    public required ReusableUnitRef Reference { get; init; }

}

public sealed record ContentFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("content")]
    [JsonRequired]
    public required IReadOnlyList<ContentNode> Content { get; init; }

}

public sealed record ActionFormItem : FormItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("action")]
    [JsonRequired]
    public required FormActionConfig Action { get; init; }

}

public sealed record FormSection
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("title")]
    [JsonRequired]
    public required InternationalizedText Title { get; init; }

    [JsonPropertyName("fields")]
    [JsonRequired]
    public required IReadOnlyList<string> Fields { get; init; }

    [JsonPropertyName("access")]
    [JsonRequired]
    public required SectionAccess Access { get; init; }

    [JsonPropertyName("layout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SectionLayout> Layout { get; init; }

    [JsonPropertyName("fieldPlacement")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, FieldPlacement>> FieldPlacement { get; init; }

    [JsonPropertyName("aspects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AspectOverlay> Aspects { get; init; }

    [JsonPropertyName("items")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<FormItem>> Items { get; init; }

}

public sealed record FieldConfig
{
    [JsonPropertyName("currencyCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> CurrencyCode { get; init; }

    [JsonPropertyName("accept")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Accept { get; init; }

    [JsonPropertyName("multiple")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Multiple { get; init; }

}

public sealed record FieldOverlay
{
    [JsonPropertyName("label")]
    [JsonRequired]
    public required InternationalizedText Label { get; init; }

    [JsonPropertyName("helpText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> HelpText { get; init; }

    [JsonPropertyName("controlHint")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ControlHint> ControlHint { get; init; }

    [JsonPropertyName("piiSensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PiiSensitivity> PiiSensitivity { get; init; }

    [JsonPropertyName("fieldReadRoles")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<RoleReference>> FieldReadRoles { get; init; }

    [JsonPropertyName("fieldWriteRoles")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<RoleReference>> FieldWriteRoles { get; init; }

    [JsonPropertyName("aspects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AspectOverlay> Aspects { get; init; }

    [JsonPropertyName("config")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FieldConfig> Config { get; init; }

}

public sealed record RuleDefinition
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("tier")]
    [JsonRequired]
    public required RuleTier Tier { get; init; }

    [JsonPropertyName("scope")]
    [JsonRequired]
    public required RuleScope Scope { get; init; }

    [JsonPropertyName("scopeTarget")]
    [JsonRequired]
    public required string ScopeTarget { get; init; }

    [JsonPropertyName("expression")]
    [JsonRequired]
    public required string Expression { get; init; }

    [JsonPropertyName("action")]
    [JsonRequired]
    public required RuleActionKind Action { get; init; }

    [JsonPropertyName("errorMessage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> ErrorMessage { get; init; }

    [JsonPropertyName("presentation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PresentationHint> Presentation { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<OutputType>))]
public enum OutputType
{
    [JsonStringEnumMemberName("Value")]
    Value,
    [JsonStringEnumMemberName("Validity")]
    Validity,
    [JsonStringEnumMemberName("Visibility")]
    Visibility,
    [JsonStringEnumMemberName("Presentation")]
    Presentation,
    [JsonStringEnumMemberName("Options")]
    Options,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<ValueState>))]
public enum ValueState
{
    [JsonStringEnumMemberName("Resolved")]
    Resolved,
    [JsonStringEnumMemberName("Error")]
    Error,
    [JsonStringEnumMemberName("Pending")]
    Pending,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<Severity>))]
public enum Severity
{
    [JsonStringEnumMemberName("info")]
    Info,
    [JsonStringEnumMemberName("warn")]
    Warn,
    [JsonStringEnumMemberName("error")]
    Error,
}

public sealed record RuleError
{
    [JsonPropertyName("code")]
    [JsonRequired]
    public required string Code { get; init; }

    [JsonPropertyName("params")]
    [JsonRequired]
    public required IReadOnlyDictionary<string, string> Params { get; init; }

}

public sealed record ComputedValue
{
    [JsonPropertyName("state")]
    [JsonRequired]
    public required ValueState State { get; init; }

    [JsonPropertyName("value")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Value { get; init; }

    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<RuleError> Error { get; init; }

}

public sealed record Validity
{
    [JsonPropertyName("ok")]
    [JsonRequired]
    public required bool Ok { get; init; }

    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<RuleError> Error { get; init; }

}

public sealed record VisibilityState
{
    [JsonPropertyName("visible")]
    [JsonRequired]
    public required bool Visible { get; init; }

    [JsonPropertyName("required")]
    [JsonRequired]
    public required bool Required { get; init; }

    [JsonPropertyName("readOnly")]
    [JsonRequired]
    public required bool ReadOnly { get; init; }

}

public sealed record PresentationOutcome
{
    [JsonPropertyName("severity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Severity?> Severity { get; init; }

    [JsonPropertyName("badge")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Badge { get; init; }

    [JsonPropertyName("styleToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> StyleToken { get; init; }

}

public sealed record OptionsOutcome
{
    [JsonPropertyName("state")]
    [JsonRequired]
    public required ValueState State { get; init; }

    [JsonPropertyName("options")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<JsonElement>> Options { get; init; }

    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<RuleError> Error { get; init; }

}

public sealed record RuleOutcome
{
    [JsonPropertyName("ruleId")]
    [JsonRequired]
    public required string RuleId { get; init; }

    [JsonPropertyName("target")]
    [JsonRequired]
    public required string Target { get; init; }

    [JsonPropertyName("outputType")]
    [JsonRequired]
    public required OutputType OutputType { get; init; }

    [JsonPropertyName("value")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ComputedValue> Value { get; init; }

    [JsonPropertyName("validity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Validity> Validity { get; init; }

    [JsonPropertyName("visibility")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<VisibilityState> Visibility { get; init; }

    [JsonPropertyName("presentation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PresentationOutcome> Presentation { get; init; }

    [JsonPropertyName("options")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<OptionsOutcome> Options { get; init; }

}

public sealed record OnSuccessConfig
{
    [JsonPropertyName("redirectUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> RedirectUrl { get; init; }

    [JsonPropertyName("hostCallback")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> HostCallback { get; init; }

}

public sealed record WizardSettings
{
    [JsonPropertyName("review")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Review { get; init; }

    [JsonPropertyName("confirmation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Confirmation { get; init; }

    [JsonPropertyName("confirmationMessage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> ConfirmationMessage { get; init; }

    [JsonPropertyName("onSuccess")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<OnSuccessConfig> OnSuccess { get; init; }

}

public sealed record FormPage
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("title")]
    [JsonRequired]
    public required InternationalizedText Title { get; init; }

    [JsonPropertyName("sections")]
    [JsonRequired]
    public required IReadOnlyList<string> Sections { get; init; }

    [JsonPropertyName("visibleWhen")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> VisibleWhen { get; init; }

    [JsonPropertyName("checks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<string>> Checks { get; init; }

}

public sealed record AsyncValidationCheck
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("connector")]
    [JsonRequired]
    public required string Connector { get; init; }

    [JsonPropertyName("field")]
    [JsonRequired]
    public required string Field { get; init; }

    [JsonPropertyName("inputs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<string>> Inputs { get; init; }

    [JsonPropertyName("failCode")]
    [JsonRequired]
    public required string FailCode { get; init; }

    [JsonPropertyName("debounceMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<decimal> DebounceMs { get; init; }

    [JsonPropertyName("allowsSensitiveInputs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> AllowsSensitiveInputs { get; init; }

}

public sealed record HarborlineOverlay
{
    [JsonPropertyName("fields")]
    [JsonRequired]
    public required IReadOnlyDictionary<string, FieldOverlay> Fields { get; init; }

    [JsonPropertyName("sections")]
    [JsonRequired]
    public required IReadOnlyList<FormSection> Sections { get; init; }

    [JsonPropertyName("rules")]
    [JsonRequired]
    public required IReadOnlyList<RuleDefinition> Rules { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Title { get; init; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Description { get; init; }

    [JsonPropertyName("aspects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AspectOverlay> Aspects { get; init; }

    [JsonPropertyName("pages")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<FormPage>> Pages { get; init; }

    [JsonPropertyName("wizard")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<WizardSettings> Wizard { get; init; }

    [JsonPropertyName("asyncChecks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<AsyncValidationCheck>> AsyncChecks { get; init; }

}

public sealed record FormDefinitionLineage
{
    [JsonPropertyName("parentDefinitionId")]
    [JsonRequired]
    public required string ParentDefinitionId { get; init; }

    [JsonPropertyName("parentVersion")]
    [JsonRequired]
    public required string ParentVersion { get; init; }

}

public sealed record IdentityRef
{
    [JsonPropertyName("scheme")]
    [JsonRequired]
    public required string Scheme { get; init; }

    [JsonPropertyName("value")]
    [JsonRequired]
    public required string Value { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<FormFieldValidationCode>))]
public enum FormFieldValidationCode
{
    [JsonStringEnumMemberName("required")]
    Required,
    [JsonStringEnumMemberName("minLength")]
    MinLength,
    [JsonStringEnumMemberName("maxLength")]
    MaxLength,
    [JsonStringEnumMemberName("pattern")]
    Pattern,
    [JsonStringEnumMemberName("minimum")]
    Minimum,
    [JsonStringEnumMemberName("maximum")]
    Maximum,
}

public sealed record FormFieldValidation
{
    [JsonPropertyName("code")]
    [JsonRequired]
    public required FormFieldValidationCode Code { get; init; }

    [JsonPropertyName("param")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Param { get; init; }

}

public sealed record FormFieldAuthoringMetadata
{
    [JsonPropertyName("type")]
    [JsonRequired]
    public required string Type { get; init; }

    [JsonPropertyName("required")]
    [JsonRequired]
    public required bool Required { get; init; }

    [JsonPropertyName("validations")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<FormFieldValidation>> Validations { get; init; }

    [JsonPropertyName("options")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<string>> Options { get; init; }

}

public sealed record FormDefinition
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("version")]
    [JsonRequired]
    public required string Version { get; init; }

    [JsonPropertyName("status")]
    [JsonRequired]
    public required FormDefinitionStatus Status { get; init; }

    [JsonPropertyName("tenant")]
    [JsonRequired]
    public required string Tenant { get; init; }

    [JsonPropertyName("owner")]
    [JsonRequired]
    public required IdentityRef Owner { get; init; }

    [JsonPropertyName("schemaRef")]
    [JsonRequired]
    public required string SchemaRef { get; init; }

    [JsonPropertyName("overlay")]
    [JsonRequired]
    public required HarborlineOverlay Overlay { get; init; }

    [JsonPropertyName("lineage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FormDefinitionLineage> Lineage { get; init; }

    [JsonPropertyName("createdAt")]
    [JsonRequired]
    public required string CreatedAt { get; init; }

    [JsonPropertyName("updatedAt")]
    [JsonRequired]
    public required string UpdatedAt { get; init; }

    [JsonPropertyName("fieldsMeta")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, FormFieldAuthoringMetadata>> FieldsMeta { get; init; }

}

public sealed record FormViewFieldRules
{
    [JsonPropertyName("visible")]
    [JsonRequired]
    public required bool Visible { get; init; }

    [JsonPropertyName("required")]
    [JsonRequired]
    public required bool Required { get; init; }

    [JsonPropertyName("readOnly")]
    [JsonRequired]
    public required bool ReadOnly { get; init; }

    [JsonPropertyName("computed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Computed { get; init; }

    [JsonPropertyName("presentationSeverity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Severity?> PresentationSeverity { get; init; }

    [JsonPropertyName("presentationBadge")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> PresentationBadge { get; init; }

    [JsonPropertyName("presentationStyleToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> PresentationStyleToken { get; init; }

}

public sealed record FormViewField
{
    [JsonPropertyName("name")]
    [JsonRequired]
    public required string Name { get; init; }

    [JsonPropertyName("label")]
    [JsonRequired]
    public required InternationalizedText Label { get; init; }

    [JsonPropertyName("helpText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText?> HelpText { get; init; }

    [JsonPropertyName("controlHint")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ControlHint { get; init; }

    [JsonPropertyName("isSensitive")]
    [JsonRequired]
    public required bool IsSensitive { get; init; }

    [JsonPropertyName("isReadable")]
    [JsonRequired]
    public required bool IsReadable { get; init; }

    [JsonPropertyName("value")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Value { get; init; }

    [JsonPropertyName("readOnly")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> ReadOnly { get; init; }

    [JsonPropertyName("presentation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PresentationOutcome> Presentation { get; init; }

    [JsonPropertyName("rules")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FormViewFieldRules> Rules { get; init; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(FieldFormViewItem), typeDiscriminator: "field")]
[JsonDerivedType(typeof(GroupFormViewItem), typeDiscriminator: "group")]
[JsonDerivedType(typeof(CollectionFormViewItem), typeDiscriminator: "collection")]
[JsonDerivedType(typeof(ContentFormViewItem), typeDiscriminator: "content")]
[JsonDerivedType(typeof(ActionFormViewItem), typeDiscriminator: "action")]
public abstract record FormViewItem;

public sealed record FieldFormViewItem : FormViewItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("field")]
    [JsonRequired]
    public required FormViewField Field { get; init; }

}

public sealed record GroupFormViewItem : FormViewItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Title { get; init; }

    [JsonPropertyName("items")]
    [JsonRequired]
    public required IReadOnlyList<FormViewItem> Items { get; init; }

    [JsonPropertyName("layout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SectionLayout> Layout { get; init; }

    [JsonPropertyName("placement")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, FieldPlacement>> Placement { get; init; }

}

public sealed record CollectionFormViewItem : FormViewItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText> Title { get; init; }

    [JsonPropertyName("items")]
    [JsonRequired]
    public required IReadOnlyList<FormViewItem> Items { get; init; }

    [JsonPropertyName("cardinality")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Cardinality> Cardinality { get; init; }

    [JsonPropertyName("table")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<CollectionTableConfig> Table { get; init; }

}

public sealed record ContentFormViewItem : FormViewItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("content")]
    [JsonRequired]
    public required IReadOnlyList<ContentNode> Content { get; init; }

}

public sealed record ActionFormViewItem : FormViewItem
{
    [JsonPropertyName("key")]
    [JsonRequired]
    public required string Key { get; init; }

    [JsonPropertyName("action")]
    [JsonRequired]
    public required FormActionConfig Action { get; init; }

}

public sealed record FormViewSection
{
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; }

    [JsonPropertyName("title")]
    [JsonRequired]
    public required InternationalizedText Title { get; init; }

    [JsonPropertyName("fields")]
    [JsonRequired]
    public required IReadOnlyList<FormViewField> Fields { get; init; }

    [JsonPropertyName("layout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SectionLayout> Layout { get; init; }

    [JsonPropertyName("fieldPlacement")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, FieldPlacement>> FieldPlacement { get; init; }

    [JsonPropertyName("items")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<FormViewItem>> Items { get; init; }

}

public sealed record FormView
{
    [JsonPropertyName("formId")]
    [JsonRequired]
    public required string FormId { get; init; }

    [JsonPropertyName("version")]
    [JsonRequired]
    public required string Version { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText?> Title { get; init; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternationalizedText?> Description { get; init; }

    [JsonPropertyName("sections")]
    [JsonRequired]
    public required IReadOnlyList<FormViewSection> Sections { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<ValidationErrorKind>))]
public enum ValidationErrorKind
{
    [JsonStringEnumMemberName("Schema")]
    Schema,
    [JsonStringEnumMemberName("ResourceBound")]
    ResourceBound,
    [JsonStringEnumMemberName("Authorization")]
    Authorization,
    [JsonStringEnumMemberName("NotFound")]
    NotFound,
}

public sealed record ValidationError
{
    [JsonPropertyName("jsonPointer")]
    [JsonRequired]
    public required string JsonPointer { get; init; }

    [JsonPropertyName("message")]
    [JsonRequired]
    public required string Message { get; init; }

    [JsonPropertyName("kind")]
    [JsonRequired]
    public required ValidationErrorKind Kind { get; init; }

    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Code { get; init; }

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyDictionary<string, string>> Params { get; init; }

}

public sealed record ValidationResult
{
    [JsonPropertyName("isValid")]
    [JsonRequired]
    public required bool IsValid { get; init; }

    [JsonPropertyName("errors")]
    [JsonRequired]
    public required IReadOnlyList<ValidationError> Errors { get; init; }

}

public sealed record FormSubmitResponse
{
    [JsonPropertyName("instanceId")]
    [JsonRequired]
    public required string InstanceId { get; init; }

}

public sealed record SubmissionBindingHeader
{
    [JsonPropertyName("schemaRef")]
    [JsonRequired]
    public required string SchemaRef { get; init; }

    [JsonPropertyName("definitionId")]
    [JsonRequired]
    public required string DefinitionId { get; init; }

    [JsonPropertyName("definitionVersion")]
    [JsonRequired]
    public required string DefinitionVersion { get; init; }

    [JsonPropertyName("engineVersion")]
    [JsonRequired]
    public required string EngineVersion { get; init; }

    [JsonPropertyName("localeChain")]
    [JsonRequired]
    public required IReadOnlyList<string> LocaleChain { get; init; }

    [JsonPropertyName("submittedAt")]
    [JsonRequired]
    public required string SubmittedAt { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<SnapshotCaptureMode>))]
public enum SnapshotCaptureMode
{
    [JsonStringEnumMemberName("none")]
    None,
    [JsonStringEnumMemberName("full-projection")]
    FullProjection,
    [JsonStringEnumMemberName("signed-dtbs-hash")]
    SignedDtbsHash,
}

public sealed record SignedDtbsHash
{
    [JsonPropertyName("hashAlgorithm")]
    [JsonRequired]
    public required string HashAlgorithm { get; init; }

    [JsonPropertyName("dtbsHash")]
    [JsonRequired]
    public required string DtbsHash { get; init; }

    [JsonPropertyName("signatureAlgorithm")]
    [JsonRequired]
    public required string SignatureAlgorithm { get; init; }

    [JsonPropertyName("signature")]
    [JsonRequired]
    public required string Signature { get; init; }

    [JsonPropertyName("publicKeyRef")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> PublicKeyRef { get; init; }

}

public sealed record SubmissionSnapshot
{
    [JsonPropertyName("mode")]
    [JsonRequired]
    public required SubmissionSnapshotModeValue Mode { get; init; }

    [JsonPropertyName("capturedAt")]
    [JsonRequired]
    public required string CapturedAt { get; init; }

    [JsonPropertyName("projection")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Projection { get; init; }

    [JsonPropertyName("signed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SignedDtbsHash> Signed { get; init; }

}

public sealed record SubmissionMintAuditPayload
{
    [JsonPropertyName("op")]
    [JsonRequired]
    public required SubmissionMintAuditPayloadOpValue Op { get; init; }

    [JsonPropertyName("form")]
    [JsonRequired]
    public required string Form { get; init; }

    [JsonPropertyName("version")]
    [JsonRequired]
    public required string Version { get; init; }

    [JsonPropertyName("encryptedFields")]
    [JsonRequired]
    public required IReadOnlyList<string> EncryptedFields { get; init; }

    [JsonPropertyName("binding")]
    [JsonRequired]
    public required SubmissionBindingHeader Binding { get; init; }

    [JsonPropertyName("snapshot")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SubmissionSnapshot> Snapshot { get; init; }

}

public sealed record DraftSaveRequest
{
    [JsonPropertyName("values")]
    [JsonRequired]
    public required IReadOnlyDictionary<string, JsonElement> Values { get; init; }

    [JsonPropertyName("subjectId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> SubjectId { get; init; }

}

public sealed record DraftSavedResponse
{
    [JsonPropertyName("caseId")]
    [JsonRequired]
    public required string CaseId { get; init; }

    [JsonPropertyName("tenantId")]
    [JsonRequired]
    public required string TenantId { get; init; }

    [JsonPropertyName("partyId")]
    [JsonRequired]
    public required string PartyId { get; init; }

}

public sealed record DraftView
{
    [JsonPropertyName("caseId")]
    [JsonRequired]
    public required string CaseId { get; init; }

    [JsonPropertyName("formId")]
    [JsonRequired]
    public required string FormId { get; init; }

    [JsonPropertyName("values")]
    [JsonRequired]
    public required IReadOnlyDictionary<string, JsonElement> Values { get; init; }

    [JsonPropertyName("subjectId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> SubjectId { get; init; }

    [JsonPropertyName("updatedAt")]
    [JsonRequired]
    public required string UpdatedAt { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<Immutability>))]
public enum Immutability
{
    [JsonStringEnumMemberName("Mutable")]
    Mutable,
    [JsonStringEnumMemberName("AppendOnly")]
    AppendOnly,
    [JsonStringEnumMemberName("WriteOnce")]
    WriteOnce,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<ProvenanceKind>))]
public enum ProvenanceKind
{
    [JsonStringEnumMemberName("Stored")]
    Stored,
    [JsonStringEnumMemberName("Computed")]
    Computed,
    [JsonStringEnumMemberName("Imported")]
    Imported,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<MeasureRole>))]
public enum MeasureRole
{
    [JsonStringEnumMemberName("None")]
    None,
    [JsonStringEnumMemberName("Measure")]
    Measure,
    [JsonStringEnumMemberName("Dimension")]
    Dimension,
}

public sealed record Tag
{
    [JsonPropertyName("system")]
    [JsonRequired]
    public required string System { get; init; }

    [JsonPropertyName("code")]
    [JsonRequired]
    public required string Code { get; init; }

    [JsonPropertyName("display")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Display { get; init; }

}

public sealed record ClassificationAspect
{
    [JsonPropertyName("tags")]
    [JsonRequired]
    public required IReadOnlyList<Tag> Tags { get; init; }

}

public sealed record AccessAspect
{
    [JsonPropertyName("readRoles")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<RoleReference>> ReadRoles { get; init; }

    [JsonPropertyName("writeRoles")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<RoleReference>> WriteRoles { get; init; }

    [JsonPropertyName("readConditionExpression")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> ReadConditionExpression { get; init; }

}

public sealed record RetentionRequirement
{
    [JsonPropertyName("regime")]
    [JsonRequired]
    public required string Regime { get; init; }

    [JsonPropertyName("floorClass")]
    [JsonRequired]
    public required string FloorClass { get; init; }

    [JsonPropertyName("minimumRetentionDays")]
    [JsonRequired]
    public required decimal MinimumRetentionDays { get; init; }

}

public sealed record ResidencyRequirement
{
    [JsonPropertyName("allowedJurisdictions")]
    [JsonRequired]
    public required IReadOnlyList<string> AllowedJurisdictions { get; init; }

    [JsonPropertyName("prohibitedJurisdictions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<string>> ProhibitedJurisdictions { get; init; }

}

public sealed record Provenance
{
    [JsonPropertyName("kind")]
    [JsonRequired]
    public required ProvenanceKind Kind { get; init; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string> Source { get; init; }

}

public sealed record LifecycleAspect
{
    [JsonPropertyName("retention")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<RetentionRequirement> Retention { get; init; }

    [JsonPropertyName("residency")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ResidencyRequirement> Residency { get; init; }

    [JsonPropertyName("immutability")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Immutability> Immutability { get; init; }

    [JsonPropertyName("provenance")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Provenance> Provenance { get; init; }

}

public sealed record DiscoveryAspect
{
    [JsonPropertyName("searchable")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Searchable { get; init; }

    [JsonPropertyName("identifier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Identifier { get; init; }

    [JsonPropertyName("facet")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Facet { get; init; }

    [JsonPropertyName("measure")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<MeasureRole> Measure { get; init; }

    [JsonPropertyName("reportable")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Reportable { get; init; }

}

public sealed record AspectOverlay
{
    [JsonPropertyName("classification")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ClassificationAspect> Classification { get; init; }

    [JsonPropertyName("access")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AccessAspect> Access { get; init; }

    [JsonPropertyName("lifecycle")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LifecycleAspect> Lifecycle { get; init; }

    [JsonPropertyName("discovery")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<DiscoveryAspect> Discovery { get; init; }

}

[JsonConverter(typeof(ClosedEnumJsonConverter<PresentationHintSeverityValue>))]
public enum PresentationHintSeverityValue
{
    [JsonStringEnumMemberName("info")]
    Info,
    [JsonStringEnumMemberName("warn")]
    Warn,
    [JsonStringEnumMemberName("error")]
    Error,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<SubmissionSnapshotModeValue>))]
public enum SubmissionSnapshotModeValue
{
    [JsonStringEnumMemberName("full-projection")]
    FullProjection,
    [JsonStringEnumMemberName("signed-dtbs-hash")]
    SignedDtbsHash,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<SubmissionMintAuditPayloadOpValue>))]
public enum SubmissionMintAuditPayloadOpValue
{
    [JsonStringEnumMemberName("form-instance-mint")]
    FormInstanceMint,
}

[JsonConverter(typeof(LayoutGapJsonConverter))]
public readonly record struct LayoutGap(int Value)
{
    public static IReadOnlySet<int> AllowedValues { get; } = new HashSet<int> { 0, 1, 2, 3, 4, 5, 6, 8 };
    public static LayoutGap From(int value) => AllowedValues.Contains(value) ? new(value) : throw new ArgumentOutOfRangeException(nameof(value));
    public static implicit operator LayoutGap(int value) => From(value);
    public static implicit operator int(LayoutGap value) => value.Value;
}

public static class FormsContractConstants
{
    public const string HARBORLINE_JSONLOGIC_V1 = "harborline-jsonlogic/v1";
}

public static class FormsContractSurface
{
    public static IReadOnlyList<string> Exports { get; } = new[]
    {
        "InternationalizedText",
        "FormDefinitionStatus",
        "PiiSensitivity",
        "RuleTier",
        "RuleScope",
        "RuleActionKind",
        "PresentationHint",
        "ControlHint",
        "SectionLayoutKind",
        "FlexDirection",
        "FlexWrap",
        "LayoutGap",
        "LayoutBreakpoint",
        "LayoutDensity",
        "LayoutAlign",
        "FieldWidth",
        "SectionLayout",
        "FieldPlacement",
        "SectionAccess",
        "FormItemKind",
        "ContentNode",
        "FormActionKind",
        "FormActionConfig",
        "ReusableUnitVersionSelector",
        "ReusableUnitRef",
        "Cardinality",
        "CollectionColumn",
        "CollectionTableConfig",
        "FormItem",
        "FormSection",
        "FieldConfig",
        "FieldOverlay",
        "RuleDefinition",
        "OutputType",
        "ValueState",
        "Severity",
        "RuleError",
        "ComputedValue",
        "Validity",
        "VisibilityState",
        "PresentationOutcome",
        "OptionsOutcome",
        "RuleOutcome",
        "OnSuccessConfig",
        "WizardSettings",
        "FormPage",
        "AsyncValidationCheck",
        "HarborlineOverlay",
        "FormDefinitionLineage",
        "IdentityRef",
        "FormFieldValidationCode",
        "FormFieldValidation",
        "FormFieldAuthoringMetadata",
        "FormDefinition",
        "FormViewFieldRules",
        "FormViewField",
        "FormViewItem",
        "FormViewSection",
        "FormView",
        "ValidationErrorKind",
        "ValidationError",
        "ValidationResult",
        "FormSubmitResponse",
        "HARBORLINE_JSONLOGIC_V1",
        "SubmissionBindingHeader",
        "SnapshotCaptureMode",
        "SignedDtbsHash",
        "SubmissionSnapshot",
        "SubmissionMintAuditPayload",
        "DraftSaveRequest",
        "DraftSavedResponse",
        "DraftView",
        "Immutability",
        "ProvenanceKind",
        "MeasureRole",
        "Tag",
        "ClassificationAspect",
        "AccessAspect",
        "RetentionRequirement",
        "ResidencyRequirement",
        "Provenance",
        "LifecycleAspect",
        "DiscoveryAspect",
        "AspectOverlay",
    };

    public static IReadOnlyDictionary<string, Type> Types { get; } =
        new Dictionary<string, Type>
    {
        ["InternationalizedText"] = typeof(InternationalizedText),
        ["FormDefinitionStatus"] = typeof(FormDefinitionStatus),
        ["PiiSensitivity"] = typeof(PiiSensitivity),
        ["RuleTier"] = typeof(RuleTier),
        ["RuleScope"] = typeof(RuleScope),
        ["RuleActionKind"] = typeof(RuleActionKind),
        ["PresentationHint"] = typeof(PresentationHint),
        ["ControlHint"] = typeof(ControlHint),
        ["SectionLayoutKind"] = typeof(SectionLayoutKind),
        ["FlexDirection"] = typeof(FlexDirection),
        ["FlexWrap"] = typeof(FlexWrap),
        ["LayoutGap"] = typeof(LayoutGap),
        ["LayoutBreakpoint"] = typeof(LayoutBreakpoint),
        ["LayoutDensity"] = typeof(LayoutDensity),
        ["LayoutAlign"] = typeof(LayoutAlign),
        ["FieldWidth"] = typeof(FieldWidth),
        ["SectionLayout"] = typeof(SectionLayout),
        ["FieldPlacement"] = typeof(FieldPlacement),
        ["SectionAccess"] = typeof(SectionAccess),
        ["FormItemKind"] = typeof(FormItemKind),
        ["ContentNode"] = typeof(ContentNode),
        ["FormActionKind"] = typeof(FormActionKind),
        ["FormActionConfig"] = typeof(FormActionConfig),
        ["ReusableUnitVersionSelector"] = typeof(ReusableUnitVersionSelector),
        ["ReusableUnitRef"] = typeof(ReusableUnitRef),
        ["Cardinality"] = typeof(Cardinality),
        ["CollectionColumn"] = typeof(CollectionColumn),
        ["CollectionTableConfig"] = typeof(CollectionTableConfig),
        ["FormItem"] = typeof(FormItem),
        ["FormSection"] = typeof(FormSection),
        ["FieldConfig"] = typeof(FieldConfig),
        ["FieldOverlay"] = typeof(FieldOverlay),
        ["RuleDefinition"] = typeof(RuleDefinition),
        ["OutputType"] = typeof(OutputType),
        ["ValueState"] = typeof(ValueState),
        ["Severity"] = typeof(Severity),
        ["RuleError"] = typeof(RuleError),
        ["ComputedValue"] = typeof(ComputedValue),
        ["Validity"] = typeof(Validity),
        ["VisibilityState"] = typeof(VisibilityState),
        ["PresentationOutcome"] = typeof(PresentationOutcome),
        ["OptionsOutcome"] = typeof(OptionsOutcome),
        ["RuleOutcome"] = typeof(RuleOutcome),
        ["OnSuccessConfig"] = typeof(OnSuccessConfig),
        ["WizardSettings"] = typeof(WizardSettings),
        ["FormPage"] = typeof(FormPage),
        ["AsyncValidationCheck"] = typeof(AsyncValidationCheck),
        ["HarborlineOverlay"] = typeof(HarborlineOverlay),
        ["FormDefinitionLineage"] = typeof(FormDefinitionLineage),
        ["IdentityRef"] = typeof(IdentityRef),
        ["FormFieldValidationCode"] = typeof(FormFieldValidationCode),
        ["FormFieldValidation"] = typeof(FormFieldValidation),
        ["FormFieldAuthoringMetadata"] = typeof(FormFieldAuthoringMetadata),
        ["FormDefinition"] = typeof(FormDefinition),
        ["FormViewFieldRules"] = typeof(FormViewFieldRules),
        ["FormViewField"] = typeof(FormViewField),
        ["FormViewItem"] = typeof(FormViewItem),
        ["FormViewSection"] = typeof(FormViewSection),
        ["FormView"] = typeof(FormView),
        ["ValidationErrorKind"] = typeof(ValidationErrorKind),
        ["ValidationError"] = typeof(ValidationError),
        ["ValidationResult"] = typeof(ValidationResult),
        ["FormSubmitResponse"] = typeof(FormSubmitResponse),
        ["SubmissionBindingHeader"] = typeof(SubmissionBindingHeader),
        ["SnapshotCaptureMode"] = typeof(SnapshotCaptureMode),
        ["SignedDtbsHash"] = typeof(SignedDtbsHash),
        ["SubmissionSnapshot"] = typeof(SubmissionSnapshot),
        ["SubmissionMintAuditPayload"] = typeof(SubmissionMintAuditPayload),
        ["DraftSaveRequest"] = typeof(DraftSaveRequest),
        ["DraftSavedResponse"] = typeof(DraftSavedResponse),
        ["DraftView"] = typeof(DraftView),
        ["Immutability"] = typeof(Immutability),
        ["ProvenanceKind"] = typeof(ProvenanceKind),
        ["MeasureRole"] = typeof(MeasureRole),
        ["Tag"] = typeof(Tag),
        ["ClassificationAspect"] = typeof(ClassificationAspect),
        ["AccessAspect"] = typeof(AccessAspect),
        ["RetentionRequirement"] = typeof(RetentionRequirement),
        ["ResidencyRequirement"] = typeof(ResidencyRequirement),
        ["Provenance"] = typeof(Provenance),
        ["LifecycleAspect"] = typeof(LifecycleAspect),
        ["DiscoveryAspect"] = typeof(DiscoveryAspect),
        ["AspectOverlay"] = typeof(AspectOverlay),
    };

    public static IReadOnlyDictionary<string, IReadOnlyList<string>> ClosedValues { get; } =
        new Dictionary<string, IReadOnlyList<string>>
    {
        ["FormDefinitionStatus"] = new[] { "Draft", "Published", "Deprecated", "Withdrawn" },
        ["PiiSensitivity"] = new[] { "None", "Sensitive" },
        ["RuleTier"] = new[] { "JsonSchema", "JsonLogic", "PowerFx" },
        ["RuleScope"] = new[] { "Field", "Section", "Schema", "Row", "Table" },
        ["RuleActionKind"] = new[] { "Visibility", "Required", "ReadOnly", "Validate", "Compute", "Presentation", "Options" },
        ["SectionLayoutKind"] = new[] { "stack", "flex", "grid" },
        ["FlexDirection"] = new[] { "row", "column" },
        ["FlexWrap"] = new[] { "nowrap", "wrap" },
        ["LayoutGap"] = new[] { "0", "1", "2", "3", "4", "5", "6", "8" },
        ["LayoutBreakpoint"] = new[] { "sm", "md", "lg" },
        ["LayoutDensity"] = new[] { "comfortable", "compact" },
        ["LayoutAlign"] = new[] { "start", "center", "end", "stretch" },
        ["FieldWidth"] = new[] { "auto", "1/4", "1/3", "1/2", "2/3", "3/4", "full" },
        ["FormItemKind"] = new[] { "field", "group", "collection", "reference", "content", "action" },
        ["FormActionKind"] = new[] { "open-url", "scroll-to-section" },
        ["OutputType"] = new[] { "Value", "Validity", "Visibility", "Presentation", "Options" },
        ["ValueState"] = new[] { "Resolved", "Error", "Pending" },
        ["Severity"] = new[] { "info", "warn", "error" },
        ["FormFieldValidationCode"] = new[] { "required", "minLength", "maxLength", "pattern", "minimum", "maximum" },
        ["ValidationErrorKind"] = new[] { "Schema", "ResourceBound", "Authorization", "NotFound" },
        ["SnapshotCaptureMode"] = new[] { "none", "full-projection", "signed-dtbs-hash" },
        ["Immutability"] = new[] { "Mutable", "AppendOnly", "WriteOnce" },
        ["ProvenanceKind"] = new[] { "Stored", "Computed", "Imported" },
        ["MeasureRole"] = new[] { "None", "Measure", "Dimension" },
    };
}

public static class FormsWire
{
    public static object Deserialize(string type, string json)
    {
        using var document = JsonDocument.Parse(json);
        FormsJson.Validate(type, document.RootElement);
        if (!FormsContractSurface.Types.TryGetValue(type, out var targetType))
            throw new FormsWireException("unknown-type", type);
        return JsonSerializer.Deserialize(document.RootElement, targetType, FormsJson.Options)
            ?? throw new FormsWireException("invalid-null", type);
    }

    public static string Serialize(string type, object value)
    {
        if (!FormsContractSurface.Types.TryGetValue(type, out var targetType))
            throw new FormsWireException("unknown-type", type);
        return JsonSerializer.Serialize(value, targetType, FormsJson.Options);
    }
}
