using Harborline.Blocks.Aggregates;
using Xunit;

namespace Harborline.Blocks.Aggregates.Tests;

public sealed class EvaluationTests
{
    [Fact] public async Task SumCountAverageMinAndMaxEvaluate() { foreach (var op in new[] { AggregateOperator.Sum, AggregateOperator.Average, AggregateOperator.Min, AggregateOperator.Max }) Assert.Equal(AggregateCellState.Value, (await TestFixture.Evaluate(Measure(op), D("2"), D("4"))).Groups.Last().Measures.Single().State); var count = TestFixture.Definition(measures: [new("m", AggregateOperator.Count, "value", AggregateValueType.Decimal, AggregateValueType.Integer, Count: AggregateCountMode.Values)]); Assert.Equal(2L, (await TestFixture.Evaluate(count, D("2"), D("4"))).Groups.Last().Measures.Single().Value); }
    [Fact] public async Task NullIgnoreSkipsNull() { var r = await TestFixture.Evaluate(Measure(AggregateOperator.Sum), D("2"), TestFixture.Row(("value", AggregateValue.Null(AggregateValueType.Decimal)))); Assert.Equal("2", Cell(r)); }
    [Fact] public async Task NullPropagateProducesNull() { var d = Measure(AggregateOperator.Sum) with { Measures = [new("m", AggregateOperator.Sum, "value", AggregateValueType.Decimal, AggregateValueType.Decimal, AggregateNullPolicy.Propagate)] }; var r = await TestFixture.Evaluate(d, D("2"), TestFixture.Row(("value", AggregateValue.Null(AggregateValueType.Decimal)))); Assert.Equal(AggregateCellState.Null, r.Groups.Last().Measures.Single().State); }
    [Fact] public async Task UnavailablePropagateProducesUnavailable() { var d = Measure(AggregateOperator.Sum) with { Measures = [new("m", AggregateOperator.Sum, "value", AggregateValueType.Decimal, AggregateValueType.Decimal, Unavailable: AggregateUnavailablePolicy.Propagate)] }; var r = await TestFixture.Evaluate(d, TestFixture.Row(("value", AggregateValue.Unavailable(AggregateValueType.Decimal)))); Assert.Equal(AggregateCellState.Unavailable, r.Groups.Last().Measures.Single().State); }
    [Fact] public async Task MissingRowFieldFails() { var error = await Assert.ThrowsAsync<AggregateException>(() => TestFixture.Evaluate(Measure(AggregateOperator.Sum), new AggregateRow(new Dictionary<string, AggregateValue>()))); Assert.Equal("aggregates.source.contract_mismatch", error.Code); }
    [Fact] public async Task ZeroDimensionsCreateOneDetailGroupForRows() { var d = Measure(AggregateOperator.Sum) with { Totals = new AggregateTotals([], false) }; Assert.Equal(AggregateGroupKind.Detail, (await TestFixture.Evaluate(d, D("1"))).Groups.Single().Kind); }
    [Fact] public async Task MultidimensionalIntersectionGroupsRows() { var d = Grouped(2); var r = await TestFixture.Evaluate(d, G("A", "X", "1"), G("A", "Y", "2")); Assert.Equal(2, r.Groups.Count); }
    [Fact] public async Task NullBucketCreatesTypedNullKey() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket); var r = await TestFixture.Evaluate(d, TestFixture.Row(("g", AggregateValue.Null(AggregateValueType.String)), ("value", TestFixture.V(AggregateValueType.Decimal, "1")))); Assert.Null(r.Groups.Single().Keys.Single().Value); }
    [Fact] public async Task NullExcludeDropsRow() { var d = OneDimension(AggregateDimensionNullPolicy.Exclude); var r = await TestFixture.Evaluate(d, TestFixture.Row(("g", AggregateValue.Null(AggregateValueType.String)), ("value", TestFixture.V(AggregateValueType.Decimal, "1")))); Assert.Empty(r.Groups); }
    [Fact] public async Task RequestedSubtotalIsEmitted() { var d = Grouped(2) with { Totals = new AggregateTotals([1], false) }; Assert.Contains((await TestFixture.Evaluate(d, G("A", "X", "1"))).Groups, group => group.Kind == AggregateGroupKind.Subtotal); }
    [Fact] public async Task RequestedGrandTotalIsEmittedForEmptyRows() { var d = Measure(AggregateOperator.Sum); Assert.Equal(AggregateGroupKind.GrandTotal, (await TestFixture.Evaluate(d)).Groups.Single().Kind); }
    [Fact] public async Task TotalIsFoldedFromOriginalRows() { var d = Grouped(1) with { Measures = [new("m", AggregateOperator.Average, "value", AggregateValueType.Decimal, AggregateValueType.Decimal)], Totals = new AggregateTotals([], true) }; var r = await TestFixture.Evaluate(d, G("A", "X", "1"), G("A", "X", "1"), G("B", "X", "10")); Assert.Equal("4", r.Groups.Last().Measures.Single().Value); }
    [Fact] public async Task OrdinalOrderingIsCaseSensitive() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket); var r = await TestFixture.Evaluate(d, O("a"), O("B")); Assert.Equal(new object?[] { "B", "a" }, r.Groups.Select(group => group.Keys[0].Value)); }
    [Fact] public async Task SourceOrderDoesNotAffectResultOrder() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket); var a = await TestFixture.Evaluate(d, O("z"), O("a")); var b = await TestFixture.Evaluate(d, O("a"), O("z")); Assert.Equal(a.Groups.Select(x => x.Keys[0].Value), b.Groups.Select(x => x.Keys[0].Value)); }
    [Fact] public async Task InputLimitFailsWholeEvaluation() { var d = Measure(AggregateOperator.Sum) with { Bounds = new AggregateBounds(1, 10, 10) }; var e = await Assert.ThrowsAsync<AggregateException>(() => TestFixture.Evaluate(d, D("1"), D("2"))); Assert.Equal("aggregates.evaluation.input_limit", e.Code); }
    [Fact] public async Task GroupLimitFailsWholeEvaluation() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket) with { Bounds = new AggregateBounds(10, 1, 10) }; var e = await Assert.ThrowsAsync<AggregateException>(() => TestFixture.Evaluate(d, O("a"), O("b"))); Assert.Equal("aggregates.evaluation.group_limit", e.Code); }
    [Fact] public async Task CellLimitFailsWholeEvaluation() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket) with { Bounds = new AggregateBounds(10, 10, 1) }; var e = await Assert.ThrowsAsync<AggregateException>(() => TestFixture.Evaluate(d, O("a"), O("b"))); Assert.Equal("aggregates.evaluation.cell_limit", e.Code); }
    [Fact] public async Task SnapshotTokenIsPropagated() => Assert.Equal("snapshot-1", (await TestFixture.Evaluate(Measure(AggregateOperator.Sum), D("1"))).Snapshot);
    [Fact] public async Task CancellationIsObserved() { using var cancellation = new CancellationTokenSource(); cancellation.Cancel(); var engine = new AggregateEngine(new TestFixture.Source([]), new TestFixture.Authorization(), new AggregateDefinitionValidator(), new AggregateHostBounds(100, 100, 100)); await Assert.ThrowsAnyAsync<OperationCanceledException>(() => engine.EvaluateAsync(new("t", "a"), Measure(AggregateOperator.Sum), cancellation.Token).AsTask()); }
    [Fact] public async Task AuthorizationOccursBeforeSourceOpen() { var source = new TestFixture.Source([]); var engine = new AggregateEngine(source, new TestFixture.Authorization(false), new AggregateDefinitionValidator(), new AggregateHostBounds(100, 100, 100)); await Assert.ThrowsAsync<AggregateException>(() => engine.EvaluateAsync(new("t", "a"), Measure(AggregateOperator.Sum)).AsTask()); Assert.Equal(0, source.Opens); }
    [Fact] public async Task FilterRunsBeforeGrouping() { var d = OneDimension(AggregateDimensionNullPolicy.Bucket) with { Filter = new AggregateComparisonFilter("g", AggregateComparisonOperator.Eq, TestFixture.V(AggregateValueType.String, "keep")) }; var r = await TestFixture.Evaluate(d, O("keep"), O("drop")); Assert.Single(r.Groups); }
    [Fact] public async Task NonTerminatingDecimalAverageFails() { var e = await Assert.ThrowsAsync<AggregateException>(() => TestFixture.Evaluate(Measure(AggregateOperator.Average), D("1"), D("1"), D("0"))); Assert.Equal("aggregates.measure.non_terminating_decimal", e.Code); }

    private static AggregateDefinition Measure(AggregateOperator op) => TestFixture.Definition(measures: [new("m", op, "value", AggregateValueType.Decimal, AggregateValueType.Decimal)]);
    private static AggregateDefinition OneDimension(AggregateDimensionNullPolicy nulls) => TestFixture.Definition(new Dictionary<string, AggregateValueType> { ["g"] = AggregateValueType.String, ["value"] = AggregateValueType.Decimal }, [new("g", "g", AggregateValueType.String, nulls, AggregateSortDirection.Asc)], totals: new AggregateTotals([], false));
    private static AggregateDefinition Grouped(int dimensions) { var fields = new Dictionary<string, AggregateValueType> { ["a"] = AggregateValueType.String, ["b"] = AggregateValueType.String, ["value"] = AggregateValueType.Decimal }; var grouping = new[] { new AggregateDimension("a", "a", AggregateValueType.String, AggregateDimensionNullPolicy.Bucket, AggregateSortDirection.Asc), new AggregateDimension("b", "b", AggregateValueType.String, AggregateDimensionNullPolicy.Bucket, AggregateSortDirection.Asc) }.Take(dimensions).ToArray(); return TestFixture.Definition(fields, grouping, totals: new AggregateTotals([], false)); }
    private static AggregateRow D(string value) => TestFixture.Row(("value", TestFixture.V(AggregateValueType.Decimal, value)));
    private static AggregateRow G(string a, string b, string value) => TestFixture.Row(("a", TestFixture.V(AggregateValueType.String, a)), ("b", TestFixture.V(AggregateValueType.String, b)), ("value", TestFixture.V(AggregateValueType.Decimal, value)));
    private static AggregateRow O(string key) => TestFixture.Row(("g", TestFixture.V(AggregateValueType.String, key)), ("value", TestFixture.V(AggregateValueType.Decimal, "1")));
    private static object? Cell(AggregateResult result) => result.Groups.Last().Measures.Single().Value;
}
