#nullable enable
#pragma warning disable CS1591

// <auto-generated />
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Harborline.Contracts.Authorization;
using Harborline.Contracts.Forms;

namespace Harborline.Contracts.Workflow;

public sealed class GuardRefJsonConverter : JsonConverter<GuardRef>
{
    public override GuardRef Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? new(reader.GetString()!) : throw new JsonException("GuardRef must be a string.");
    public override void Write(Utf8JsonWriter writer, GuardRef value, JsonSerializerOptions options) => writer.WriteStringValue(value.Value);
}

public sealed class WorkflowEffectParamsJsonConverter : JsonConverter<WorkflowEffectParams>
{
    public override WorkflowEffectParams Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) =>
        new(JsonSerializer.Deserialize<IReadOnlyDictionary<string, JsonElement>>(ref reader, options)
            ?? throw new JsonException("WorkflowEffectParams must be an object."));
    public override void Write(Utf8JsonWriter writer, WorkflowEffectParams value, JsonSerializerOptions options) =>
        JsonSerializer.Serialize(writer, value.Values, options);
}

public sealed class WorkflowActionTargetJsonConverter : JsonConverter<WorkflowActionTarget>
{
    public override WorkflowActionTarget Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var value = document.RootElement;
        var hasState = value.TryGetProperty("state", out var state);
        var hasTransition = value.TryGetProperty("transition", out var transition);
        if (value.ValueKind != JsonValueKind.Object || hasState == hasTransition)
            throw new WorkflowWireException("exclusive-union-mismatch", "WorkflowActionBinding.on");
        if (hasState && state.ValueKind == JsonValueKind.String) return new WorkflowStateActionTarget(state.GetString()!);
        if (hasTransition && transition.ValueKind == JsonValueKind.String) return new WorkflowTransitionActionTarget(transition.GetString()!);
        throw new WorkflowWireException("invalid-string", "WorkflowActionBinding.on");
    }

    public override void Write(Utf8JsonWriter writer, WorkflowActionTarget value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
        if (value is WorkflowStateActionTarget state) writer.WriteString("state", state.State);
        else if (value is WorkflowTransitionActionTarget transition) writer.WriteString("transition", transition.Transition);
        else throw new JsonException("Unknown WorkflowActionTarget subtype.");
        writer.WriteEndObject();
    }
}

public sealed class WorkflowWireException(string code, string type, string? detail = null)
    : JsonException($"{code}: {type}{(detail is null ? string.Empty : $" ({detail})")}")
{
    public string Code { get; } = code;
    public string WireType { get; } = type;
    public string? Detail { get; } = detail;
}

public static class WorkflowContractSurface
{
    public static IReadOnlyList<string> Exports { get; } =
    [
        "WorkflowDefinitionStatus", "WorkflowMutability", "WorkflowStateKind", "WorkflowViewHint",
        "WorkflowTriggerKind", "WorkflowActionKind", "ActionClassification", "GuardRef", "WorkflowState",
        "WorkflowTransition", "WorkflowTriggerBinding", "WorkflowEffectParams", "WorkflowActionBinding",
        "WorkflowDefinitionLineage", "FormDefinitionRef", "WorkflowDefinition",
    ];

    public static IReadOnlyDictionary<string, IReadOnlyList<string>> ClosedValues { get; } =
        new Dictionary<string, IReadOnlyList<string>>
        {
            ["WorkflowDefinitionStatus"] = ["Draft", "Published", "Deprecated", "Withdrawn"],
            ["WorkflowMutability"] = ["Locked", "Editable"],
            ["WorkflowStateKind"] = ["Normal", "Terminal"],
            ["WorkflowViewHint"] = ["flow", "gantt", "kanban"],
            ["WorkflowTriggerKind"] = ["Event", "Schedule", "HumanAction", "DependencyComplete"],
            ["WorkflowActionKind"] = ["Notify", "CreateRecord", "UpdateField", "InvokeService", "StartSubProcess", "EmitEvent"],
            ["ActionClassification"] = ["CP", "AP"],
        };
}

public static class WorkflowWire
{
    private static readonly IReadOnlyDictionary<string, Type> Types = new Dictionary<string, Type>
    {
        ["WorkflowDefinitionStatus"] = typeof(WorkflowDefinitionStatus), ["WorkflowMutability"] = typeof(WorkflowMutability),
        ["WorkflowStateKind"] = typeof(WorkflowStateKind), ["WorkflowViewHint"] = typeof(WorkflowViewHint),
        ["WorkflowTriggerKind"] = typeof(WorkflowTriggerKind), ["WorkflowActionKind"] = typeof(WorkflowActionKind),
        ["ActionClassification"] = typeof(ActionClassification), ["GuardRef"] = typeof(GuardRef),
        ["WorkflowState"] = typeof(WorkflowState), ["WorkflowTransition"] = typeof(WorkflowTransition),
        ["WorkflowTriggerBinding"] = typeof(WorkflowTriggerBinding), ["WorkflowEffectParams"] = typeof(WorkflowEffectParams),
        ["WorkflowActionBinding"] = typeof(WorkflowActionBinding), ["WorkflowDefinitionLineage"] = typeof(WorkflowDefinitionLineage),
        ["FormDefinitionRef"] = typeof(FormDefinitionRef), ["WorkflowDefinition"] = typeof(WorkflowDefinition),
    };

    public static object Deserialize(string type, string json)
    {
        using var document = JsonDocument.Parse(json);
        Validate(type, document.RootElement);
        if (!Types.TryGetValue(type, out var target)) throw new WorkflowWireException("unknown-type", type);
        try
        {
            return JsonSerializer.Deserialize(document.RootElement, target, FormsJson.Options)
                ?? throw new WorkflowWireException("invalid-null", type);
        }
        catch (WorkflowWireException) { throw; }
        catch (JsonException error) { throw new WorkflowWireException("invalid-wire-value", type, error.Message); }
    }

    public static string Serialize(string type, object value)
    {
        if (!Types.TryGetValue(type, out var target)) throw new WorkflowWireException("unknown-type", type);
        return JsonSerializer.Serialize(value, target, FormsJson.Options);
    }

    public static void Validate(string type, JsonElement value)
    {
        if (WorkflowContractSurface.ClosedValues.TryGetValue(type, out var values))
        {
            Require(value.ValueKind == JsonValueKind.String && values.Contains(value.GetString()!), "unknown-closed-value", type);
            return;
        }
        switch (type)
        {
            case "GuardRef": String(value, type); break;
            case "WorkflowEffectParams": Object(value, type); break;
            case "WorkflowState": State(value); break;
            case "WorkflowTransition": Transition(value); break;
            case "WorkflowTriggerBinding": Trigger(value); break;
            case "WorkflowActionBinding": Action(value); break;
            case "WorkflowDefinitionLineage": Lineage(value); break;
            case "FormDefinitionRef": FormRef(value); break;
            case "WorkflowDefinition": Definition(value); break;
            default: throw new WorkflowWireException("unknown-type", type);
        }
    }

    private static void State(JsonElement value)
    {
        Object(value, "WorkflowState");
        String(Required(value, "id", "WorkflowState"), "WorkflowState.id");
        FormsJson.Validate("InternationalizedText", Required(value, "label", "WorkflowState"));
        Validate("WorkflowStateKind", Required(value, "kind", "WorkflowState"));
        Optional(value, "viewHint", item => Validate("WorkflowViewHint", item));
    }

    private static void Transition(JsonElement value)
    {
        Object(value, "WorkflowTransition");
        foreach (var name in new[] { "id", "from", "on", "to" }) String(Required(value, name, "WorkflowTransition"), $"WorkflowTransition.{name}");
        Optional(value, "guard", item => String(item, "WorkflowTransition.guard"));
        Optional(value, "requiredRoles", item => RoleArray(item, "WorkflowTransition.requiredRoles"));
    }

    private static void Trigger(JsonElement value)
    {
        Object(value, "WorkflowTriggerBinding");
        String(Required(value, "id", "WorkflowTriggerBinding"), "WorkflowTriggerBinding.id");
        Validate("WorkflowTriggerKind", Required(value, "kind", "WorkflowTriggerBinding"));
        foreach (var name in new[] { "eventType", "rrule", "task", "dependency" }) Optional(value, name, item => String(item, $"WorkflowTriggerBinding.{name}"));
    }

    private static void Action(JsonElement value)
    {
        Object(value, "WorkflowActionBinding");
        String(Required(value, "id", "WorkflowActionBinding"), "WorkflowActionBinding.id");
        var on = Required(value, "on", "WorkflowActionBinding");
        Object(on, "WorkflowActionBinding.on");
        var hasState = on.TryGetProperty("state", out var state);
        var hasTransition = on.TryGetProperty("transition", out var transition);
        Require(hasState != hasTransition, "exclusive-union-mismatch", "WorkflowActionBinding.on");
        String(hasState ? state : transition, "WorkflowActionBinding.on");
        Validate("WorkflowActionKind", Required(value, "kind", "WorkflowActionBinding"));
        String(Required(value, "capabilityRef", "WorkflowActionBinding"), "WorkflowActionBinding.capabilityRef");
        Validate("ActionClassification", Required(value, "classification", "WorkflowActionBinding"));
        Optional(value, "condition", item => String(item, "WorkflowActionBinding.condition"));
        Optional(value, "requiredRoles", item => RoleArray(item, "WorkflowActionBinding.requiredRoles"));
        Optional(value, "params", item => Object(item, "WorkflowEffectParams"));
    }

    private static void Lineage(JsonElement value)
    {
        Object(value, "WorkflowDefinitionLineage");
        String(Required(value, "parentDefinitionKey", "WorkflowDefinitionLineage"), "WorkflowDefinitionLineage.parentDefinitionKey");
        String(Required(value, "parentVersion", "WorkflowDefinitionLineage"), "WorkflowDefinitionLineage.parentVersion");
    }

    private static void FormRef(JsonElement value)
    {
        Object(value, "FormDefinitionRef");
        String(Required(value, "formId", "FormDefinitionRef"), "FormDefinitionRef.formId");
        String(Required(value, "version", "FormDefinitionRef"), "FormDefinitionRef.version");
    }

    private static void Definition(JsonElement value)
    {
        Object(value, "WorkflowDefinition");
        foreach (var name in new[] { "key", "version", "tenant", "initialState", "createdAt", "updatedAt" }) String(Required(value, name, "WorkflowDefinition"), $"WorkflowDefinition.{name}");
        Validate("WorkflowDefinitionStatus", Required(value, "status", "WorkflowDefinition"));
        FormsJson.Validate("IdentityRef", Required(value, "owner", "WorkflowDefinition"));
        FormsJson.Validate("InternationalizedText", Required(value, "title", "WorkflowDefinition"));
        Optional(value, "description", item => FormsJson.Validate("InternationalizedText", item));
        Optional(value, "subjectFormRef", FormRef);
        Validate("WorkflowMutability", Required(value, "mutability", "WorkflowDefinition"));
        Array(value, "states", "WorkflowDefinition", State);
        Array(value, "transitions", "WorkflowDefinition", Transition);
        Array(value, "triggers", "WorkflowDefinition", Trigger);
        Array(value, "actions", "WorkflowDefinition", Action);
        Array(value, "guards", "WorkflowDefinition", item => FormsJson.Validate("RuleDefinition", item));
        Optional(value, "lineage", Lineage);
    }

    private static JsonElement Required(JsonElement source, string name, string type)
    {
        Require(source.TryGetProperty(name, out var value), "missing-required-property", type, name);
        return value;
    }
    private static void Optional(JsonElement source, string name, Action<JsonElement> validate) { if (source.TryGetProperty(name, out var value)) validate(value); }
    private static void Array(JsonElement source, string name, string type, Action<JsonElement> validate)
    {
        var value = Required(source, name, type); Require(value.ValueKind == JsonValueKind.Array, "invalid-array", $"{type}.{name}");
        foreach (var item in value.EnumerateArray()) validate(item);
    }
    private static void Object(JsonElement value, string type) => Require(value.ValueKind == JsonValueKind.Object, "invalid-object", type);
    private static void String(JsonElement value, string type) => Require(value.ValueKind == JsonValueKind.String, "invalid-string", type);
    private static void RoleArray(JsonElement value, string type)
    {
        Require(value.ValueKind == JsonValueKind.Array, "invalid-array", type);
        foreach (var role in value.EnumerateArray())
        {
            Object(role, "RoleReference");
            var vocabulary = Required(role, "vocabulary", "RoleReference");
            String(vocabulary, "RoleReference.vocabulary");
            Require(vocabulary.GetString() is RoleVocabularies.Platform or RoleVocabularies.Domain, "unknown-role-vocabulary", "RoleReference");
            String(Required(role, "name", "RoleReference"), "RoleReference.name");
        }
    }
    private static void Require(bool condition, string code, string type, string? detail = null) { if (!condition) throw new WorkflowWireException(code, type, detail); }
}

public static class WorkflowAdmissionCodes
{
    public const string ClassificationMismatch = "workflow.admission.classification_mismatch";
    public const string CpReachableWithoutHumanTask = "workflow.admission.cp_reachable_without_human_task";
    public const string InitialStateMissing = "workflow.admission.initial_state_missing";
    public const string DeadEndState = "workflow.admission.dead_end_state";
    public const string TerminalHasOutgoing = "workflow.admission.terminal_has_outgoing";
    public const string UnreachableState = "workflow.admission.unreachable_state";
    public const string DanglingReference = "workflow.admission.dangling_reference";
    public const string ActionBindingInvalid = "workflow.admission.action_binding_invalid";
    public const string DuplicateId = "workflow.admission.duplicate_id";
    public const string UnknownRoleReference = "workflow.admission.unknown_role_reference";
}

public sealed record WorkflowAdmissionViolation(string Code, string Message, string Locator);
public sealed record WorkflowAdmissionResult(bool IsValid, IReadOnlyList<WorkflowAdmissionViolation> Violations);
public interface IWorkflowAuthorityResolver { ActionClassification AuthorityOf(string capabilityRef); }

public sealed class ImmutableWorkflowAuthorityResolver : IWorkflowAuthorityResolver
{
    private readonly IReadOnlyDictionary<string, ActionClassification> _registry;
    public ImmutableWorkflowAuthorityResolver(IReadOnlyDictionary<string, ActionClassification> registry)
    {
        foreach (var (capabilityRef, classification) in registry)
            if (classification is not ActionClassification.CP and not ActionClassification.AP)
                throw new ArgumentOutOfRangeException(nameof(registry), $"Unknown authority classification for '{capabilityRef}'.");
        _registry = new Dictionary<string, ActionClassification>(registry, StringComparer.Ordinal);
    }
    public ActionClassification AuthorityOf(string capabilityRef) => _registry.TryGetValue(capabilityRef, out var value) ? value : ActionClassification.CP;
}

public static class WorkflowAdmissionValidator
{
    public static WorkflowAdmissionResult Validate(WorkflowDefinition definition, IWorkflowAuthorityResolver authority, RoleVocabulary? roleVocabulary = null)
    {
        var violations = new List<WorkflowAdmissionViolation>();
        void Add(string code, string message, string locator) => violations.Add(new(code, message, locator));
        var stateIds = Unique(definition.States, row => row.Id, "state", Add);
        var triggerById = UniqueMap(definition.Triggers, row => row.Id, "trigger", Add);
        var transitionById = UniqueMap(definition.Transitions, row => row.Id, "transition", Add);
        _ = Unique(definition.Actions, row => row.Id, "action", Add);
        var guardIds = Unique(definition.Guards, row => row.Id, "guard", Add);

        if (!stateIds.Contains(definition.InitialState)) Add(WorkflowAdmissionCodes.InitialStateMissing, "initial state does not exist", definition.InitialState);
        foreach (var transition in definition.Transitions)
        {
            if (!stateIds.Contains(transition.From) || !stateIds.Contains(transition.To) || !triggerById.ContainsKey(transition.On))
                Add(WorkflowAdmissionCodes.DanglingReference, "transition contains a dangling reference", transition.Id);
            if (transition.Guard.HasValue && !guardIds.Contains(transition.Guard.Value.Value))
                Add(WorkflowAdmissionCodes.DanglingReference, "transition guard does not exist", transition.Id);
            if (roleVocabulary is not null && transition.RequiredRoles.HasValue
                && transition.RequiredRoles.Value!.Any(role => roleVocabulary.Resolve(role) is null))
                Add(WorkflowAdmissionCodes.UnknownRoleReference, "transition requires an unknown role", transition.Id);
        }
        foreach (var action in definition.Actions)
        {
            if (action.On is WorkflowStateActionTarget state && !stateIds.Contains(state.State)) Add(WorkflowAdmissionCodes.DanglingReference, "action state does not exist", action.Id);
            else if (action.On is WorkflowTransitionActionTarget transition && !transitionById.ContainsKey(transition.Transition)) Add(WorkflowAdmissionCodes.DanglingReference, "action transition does not exist", action.Id);
            else if (action.On is not WorkflowStateActionTarget and not WorkflowTransitionActionTarget) Add(WorkflowAdmissionCodes.ActionBindingInvalid, "action target is invalid", action.Id);
            if (action.Condition.HasValue && !guardIds.Contains(action.Condition.Value.Value)) Add(WorkflowAdmissionCodes.DanglingReference, "action condition does not exist", action.Id);
            if (roleVocabulary is not null && action.RequiredRoles.HasValue
                && action.RequiredRoles.Value!.Any(role => roleVocabulary.Resolve(role) is null))
                Add(WorkflowAdmissionCodes.UnknownRoleReference, "action requires an unknown role", action.Id);
        }

        if (stateIds.Contains(definition.InitialState))
        {
            var reachable = Reachable(definition);
            var outgoing = definition.Transitions.Select(row => row.From).ToHashSet(StringComparer.Ordinal);
            foreach (var state in definition.States)
            {
                if (!reachable.Contains(state.Id)) Add(WorkflowAdmissionCodes.UnreachableState, "state is unreachable", state.Id);
                else if (state.Kind != WorkflowStateKind.Terminal && !outgoing.Contains(state.Id)) Add(WorkflowAdmissionCodes.DeadEndState, "state is a dead end", state.Id);
                if (state.Kind == WorkflowStateKind.Terminal && outgoing.Contains(state.Id)) Add(WorkflowAdmissionCodes.TerminalHasOutgoing, "terminal state has outgoing transition", state.Id);
            }
            foreach (var action in definition.Actions)
            {
                var derived = authority.AuthorityOf(action.CapabilityRef);
                if (action.Classification != derived) { Add(WorkflowAdmissionCodes.ClassificationMismatch, "declared classification does not match authority registry", action.Id); continue; }
                if (derived == ActionClassification.CP && FiresWithoutHumanGate(action, definition, transitionById, triggerById))
                    Add(WorkflowAdmissionCodes.CpReachableWithoutHumanTask, "CP action can fire without a human gate", action.Id);
            }
        }
        return new(violations.Count == 0, violations);
    }

    private static HashSet<string> Unique<T>(IEnumerable<T> rows, Func<T, string> id, string kind, Action<string, string, string> add)
    {
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var row in rows) if (!ids.Add(id(row))) add(WorkflowAdmissionCodes.DuplicateId, $"duplicate {kind} id", id(row));
        return ids;
    }
    private static Dictionary<string, T> UniqueMap<T>(IEnumerable<T> rows, Func<T, string> id, string kind, Action<string, string, string> add)
    {
        var map = new Dictionary<string, T>(StringComparer.Ordinal);
        foreach (var row in rows) { if (map.ContainsKey(id(row))) add(WorkflowAdmissionCodes.DuplicateId, $"duplicate {kind} id", id(row)); map[id(row)] = row; }
        return map;
    }
    private static HashSet<string> Reachable(WorkflowDefinition definition)
    {
        var visited = new HashSet<string>(StringComparer.Ordinal) { definition.InitialState }; var queue = new Queue<string>(); queue.Enqueue(definition.InitialState);
        while (queue.TryDequeue(out var state)) foreach (var transition in definition.Transitions.Where(row => row.From == state)) if (visited.Add(transition.To)) queue.Enqueue(transition.To);
        return visited;
    }
    private static bool FiresWithoutHumanGate(WorkflowActionBinding action, WorkflowDefinition definition, IReadOnlyDictionary<string, WorkflowTransition> transitions, IReadOnlyDictionary<string, WorkflowTriggerBinding> triggers)
    {
        bool Human(string trigger) => triggers.TryGetValue(trigger, out var binding) && binding.Kind == WorkflowTriggerKind.HumanAction;
        if (action.On is WorkflowTransitionActionTarget transition) return transitions.TryGetValue(transition.Transition, out var binding) && !Human(binding.On);
        if (action.On is not WorkflowStateActionTarget state) return false;
        if (state.State == definition.InitialState) return true;
        var incoming = definition.Transitions.Where(row => row.To == state.State).ToArray();
        return incoming.Length == 0 || incoming.Any(row => !Human(row.On));
    }
}
