#nullable enable
#pragma warning disable CS1591

// <auto-generated />
using System.Text.Json;
using System.Text.Json.Serialization;
using Harborline.Contracts.Authorization;
using Harborline.Contracts.Forms;

namespace Harborline.Contracts.Workflow;

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowDefinitionStatus>))]
public enum WorkflowDefinitionStatus
{
    [JsonStringEnumMemberName("Draft")] Draft,
    [JsonStringEnumMemberName("Published")] Published,
    [JsonStringEnumMemberName("Deprecated")] Deprecated,
    [JsonStringEnumMemberName("Withdrawn")] Withdrawn,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowMutability>))]
public enum WorkflowMutability
{
    [JsonStringEnumMemberName("Locked")] Locked,
    [JsonStringEnumMemberName("Editable")] Editable,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowStateKind>))]
public enum WorkflowStateKind
{
    [JsonStringEnumMemberName("Normal")] Normal,
    [JsonStringEnumMemberName("Terminal")] Terminal,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowViewHint>))]
public enum WorkflowViewHint
{
    [JsonStringEnumMemberName("flow")] Flow,
    [JsonStringEnumMemberName("gantt")] Gantt,
    [JsonStringEnumMemberName("kanban")] Kanban,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowTriggerKind>))]
public enum WorkflowTriggerKind
{
    [JsonStringEnumMemberName("Event")] Event,
    [JsonStringEnumMemberName("Schedule")] Schedule,
    [JsonStringEnumMemberName("HumanAction")] HumanAction,
    [JsonStringEnumMemberName("DependencyComplete")] DependencyComplete,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<WorkflowActionKind>))]
public enum WorkflowActionKind
{
    [JsonStringEnumMemberName("Notify")] Notify,
    [JsonStringEnumMemberName("CreateRecord")] CreateRecord,
    [JsonStringEnumMemberName("UpdateField")] UpdateField,
    [JsonStringEnumMemberName("InvokeService")] InvokeService,
    [JsonStringEnumMemberName("StartSubProcess")] StartSubProcess,
    [JsonStringEnumMemberName("EmitEvent")] EmitEvent,
}

[JsonConverter(typeof(ClosedEnumJsonConverter<ActionClassification>))]
public enum ActionClassification
{
    [JsonStringEnumMemberName("CP")] CP,
    [JsonStringEnumMemberName("AP")] AP,
}

[JsonConverter(typeof(GuardRefJsonConverter))]
public readonly record struct GuardRef(string Value)
{
    public static implicit operator GuardRef(string value) => new(value);
    public static implicit operator string(GuardRef value) => value.Value;
    public override string ToString() => Value;
}

[JsonConverter(typeof(WorkflowEffectParamsJsonConverter))]
public readonly record struct WorkflowEffectParams(IReadOnlyDictionary<string, JsonElement> Values);

public sealed record WorkflowState
{
    [JsonPropertyName("id"), JsonRequired] public required string Id { get; init; }
    [JsonPropertyName("label"), JsonRequired] public required InternationalizedText Label { get; init; }
    [JsonPropertyName("kind"), JsonRequired] public required WorkflowStateKind Kind { get; init; }
    [JsonPropertyName("viewHint"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<WorkflowViewHint> ViewHint { get; init; }
}

public sealed record WorkflowTransition
{
    [JsonPropertyName("id"), JsonRequired] public required string Id { get; init; }
    [JsonPropertyName("from"), JsonRequired] public required string From { get; init; }
    [JsonPropertyName("on"), JsonRequired] public required string On { get; init; }
    [JsonPropertyName("to"), JsonRequired] public required string To { get; init; }
    [JsonPropertyName("guard"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<GuardRef> Guard { get; init; }
    [JsonPropertyName("requiredRoles"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<IReadOnlyList<RoleReference>> RequiredRoles { get; init; }
}

public sealed record WorkflowTriggerBinding
{
    [JsonPropertyName("id"), JsonRequired] public required string Id { get; init; }
    [JsonPropertyName("kind"), JsonRequired] public required WorkflowTriggerKind Kind { get; init; }
    [JsonPropertyName("eventType"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<string> EventType { get; init; }
    [JsonPropertyName("rrule"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<string> Rrule { get; init; }
    [JsonPropertyName("task"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<string> Task { get; init; }
    [JsonPropertyName("dependency"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<string> Dependency { get; init; }
}

[JsonConverter(typeof(WorkflowActionTargetJsonConverter))]
public abstract record WorkflowActionTarget;
public sealed record WorkflowStateActionTarget(string State) : WorkflowActionTarget;
public sealed record WorkflowTransitionActionTarget(string Transition) : WorkflowActionTarget;

public sealed record WorkflowActionBinding
{
    [JsonPropertyName("id"), JsonRequired] public required string Id { get; init; }
    [JsonPropertyName("on"), JsonRequired] public required WorkflowActionTarget On { get; init; }
    [JsonPropertyName("kind"), JsonRequired] public required WorkflowActionKind Kind { get; init; }
    [JsonPropertyName("capabilityRef"), JsonRequired] public required string CapabilityRef { get; init; }
    [JsonPropertyName("classification"), JsonRequired] public required ActionClassification Classification { get; init; }
    [JsonPropertyName("condition"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<GuardRef> Condition { get; init; }
    [JsonPropertyName("requiredRoles"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<IReadOnlyList<RoleReference>> RequiredRoles { get; init; }
    [JsonPropertyName("params"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<WorkflowEffectParams> Params { get; init; }
}

public sealed record WorkflowDefinitionLineage
{
    [JsonPropertyName("parentDefinitionKey"), JsonRequired] public required string ParentDefinitionKey { get; init; }
    [JsonPropertyName("parentVersion"), JsonRequired] public required string ParentVersion { get; init; }
}

public sealed record FormDefinitionRef
{
    [JsonPropertyName("formId"), JsonRequired] public required string FormId { get; init; }
    [JsonPropertyName("version"), JsonRequired] public required string Version { get; init; }
}

public sealed record WorkflowDefinition
{
    [JsonPropertyName("key"), JsonRequired] public required string Key { get; init; }
    [JsonPropertyName("version"), JsonRequired] public required string Version { get; init; }
    [JsonPropertyName("status"), JsonRequired] public required WorkflowDefinitionStatus Status { get; init; }
    [JsonPropertyName("tenant"), JsonRequired] public required string Tenant { get; init; }
    [JsonPropertyName("owner"), JsonRequired] public required IdentityRef Owner { get; init; }
    [JsonPropertyName("title"), JsonRequired] public required InternationalizedText Title { get; init; }
    [JsonPropertyName("description"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<InternationalizedText> Description { get; init; }
    [JsonPropertyName("subjectFormRef"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<FormDefinitionRef> SubjectFormRef { get; init; }
    [JsonPropertyName("mutability"), JsonRequired] public required WorkflowMutability Mutability { get; init; }
    [JsonPropertyName("initialState"), JsonRequired] public required string InitialState { get; init; }
    [JsonPropertyName("states"), JsonRequired] public required IReadOnlyList<WorkflowState> States { get; init; }
    [JsonPropertyName("transitions"), JsonRequired] public required IReadOnlyList<WorkflowTransition> Transitions { get; init; }
    [JsonPropertyName("triggers"), JsonRequired] public required IReadOnlyList<WorkflowTriggerBinding> Triggers { get; init; }
    [JsonPropertyName("actions"), JsonRequired] public required IReadOnlyList<WorkflowActionBinding> Actions { get; init; }
    [JsonPropertyName("guards"), JsonRequired] public required IReadOnlyList<RuleDefinition> Guards { get; init; }
    [JsonPropertyName("lineage"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] public Optional<WorkflowDefinitionLineage> Lineage { get; init; }
    [JsonPropertyName("createdAt"), JsonRequired] public required string CreatedAt { get; init; }
    [JsonPropertyName("updatedAt"), JsonRequired] public required string UpdatedAt { get; init; }
}
