namespace Harborline.Kernel.WorkItems;

/// <summary>Storage transaction generated by the kernel after context and request admission.</summary>
public sealed record WorkItemCommit
{
    /// <summary>Current tenant wire identifier.</summary>
    public required string TenantId { get; init; }
    /// <summary>Canonical request fingerprint.</summary>
    public required string Fingerprint { get; init; }
    /// <summary>Retry key scoped to tenant and operation.</summary>
    public required string IdempotencyKey { get; init; }
    /// <summary>Actor derived from the current authenticated host scope.</summary>
    public required string ActorId { get; init; }
    /// <summary>New immutable snapshot.</summary>
    public required WorkItemSnapshot Snapshot { get; init; }
    /// <summary>Append-only event.</summary>
    public required WorkItemEvent Event { get; init; }
    /// <summary>Replay result.</summary>
    public required string ResultJson { get; init; }
    /// <summary>Optional immutable outbox messages.</summary>
    public IReadOnlyList<WorkItemOutboxMessage> Outbox { get; init; } = Array.Empty<WorkItemOutboxMessage>();
    /// <summary>Expected prior version, or null for create.</summary>
    public long? ExpectedVersion { get; init; }
    /// <summary>Expected prior step, or null for create.</summary>
    public string? ExpectedStep { get; init; }
}

/// <summary>Append-only work-item history event.</summary>
public sealed record WorkItemEvent(
    string WorkItemId,
    long Sequence,
    int Iteration,
    string Step,
    string Action,
    string DataJson,
    DateTimeOffset OccurredAt);

/// <summary>Actor audit committed in the same transaction as work-item state.</summary>
public sealed record WorkItemAudit(
    string WorkItemId,
    long WorkItemVersion,
    string ActorId,
    string Action,
    DateTimeOffset OccurredAt);

/// <summary>Fingerprint-bound retry receipt.</summary>
public sealed record WorkItemIdempotencyReceipt(
    string Key,
    string Fingerprint,
    WorkItemSnapshot Snapshot,
    string ResultJson);

/// <summary>Provider-neutral atomic persistence port.</summary>
public interface IWorkItemStore
{
    /// <summary>Loads a tenant-scoped snapshot.</summary>
    Task<WorkItemSnapshot?> GetAsync(string tenantId, string workItemId, CancellationToken cancellationToken = default);
    /// <summary>Lists open tenant-scoped snapshots.</summary>
    Task<IReadOnlyList<WorkItemSnapshot>> ListOpenAsync(string tenantId, CancellationToken cancellationToken = default);
    /// <summary>Loads a retry receipt scoped to tenant and key.</summary>
    Task<WorkItemIdempotencyReceipt?> GetReceiptAsync(string tenantId, string idempotencyKey, CancellationToken cancellationToken = default);
    /// <summary>Commits create state, event, receipt, audit, and outbox atomically.</summary>
    Task<WorkItemStoreResult> CommitCreateAsync(WorkItemCommit commit, CancellationToken cancellationToken = default);
    /// <summary>Commits a version-guarded transition atomically.</summary>
    Task<WorkItemStoreResult> CommitTransitionAsync(WorkItemCommit commit, CancellationToken cancellationToken = default);
}

/// <summary>Atomic store result.</summary>
public sealed record WorkItemStoreResult(WorkItemMutationDisposition Disposition, WorkItemIdempotencyReceipt? Receipt);

/// <summary>Optional inspection port for event, audit, and outbox delivery adapters.</summary>
public interface IWorkItemJournalReader
{
    /// <summary>Returns current-tenant history for one item.</summary>
    Task<IReadOnlyList<WorkItemEvent>> ReadEventsAsync(string tenantId, string workItemId, CancellationToken cancellationToken = default);
    /// <summary>Returns current-tenant audit records for one item.</summary>
    Task<IReadOnlyList<WorkItemAudit>> ReadAuditAsync(string tenantId, string workItemId, CancellationToken cancellationToken = default);
    /// <summary>Returns committed current-tenant outbox messages.</summary>
    Task<IReadOnlyList<WorkItemOutboxMessage>> ReadOutboxAsync(string tenantId, CancellationToken cancellationToken = default);
}
