// Generated from the frozen Workflow contract. Do not edit by hand.
// @ts-nocheck
import {readFormsWire} from './wire.js'

const closedValues = Object.freeze({"WorkflowDefinitionStatus":["Draft","Published","Deprecated","Withdrawn"],"WorkflowMutability":["Locked","Editable"],"WorkflowStateKind":["Normal","Terminal"],"WorkflowViewHint":["flow","gantt","kanban"],"WorkflowTriggerKind":["Event","Schedule","HumanAction","DependencyComplete"],"WorkflowActionKind":["Notify","CreateRecord","UpdateField","InvokeService","StartSubProcess","EmitEvent"],"ActionClassification":["CP","AP"]});
const declarations = Object.freeze(["WorkflowDefinitionStatus","WorkflowMutability","WorkflowStateKind","WorkflowViewHint","WorkflowTriggerKind","WorkflowActionKind","ActionClassification","GuardRef","WorkflowState","WorkflowTransition","WorkflowTriggerBinding","WorkflowEffectParams","WorkflowActionBinding","WorkflowDefinitionLineage","FormDefinitionRef","WorkflowDefinition"]);

function fail(code, type, detail) { throw new TypeError(`${code}: ${type}${detail ? ` (${detail})` : ""}`) }
function object(value, type) { if (value === null || Array.isArray(value) || typeof value !== 'object') fail('invalid-object', type); return value }
function string(value, type) { if (typeof value !== 'string') fail('invalid-string', type); return value }
function array(value, type, read) { if (!Array.isArray(value)) fail('invalid-array', type); return value.map(read) }
function required(source, name, type, read) { if (!Object.hasOwn(source,name)) fail('missing-required-property',type,name); return read(source[name]) }
function optional(source, name, read) { return Object.hasOwn(source, name) ? {[name]: read(source[name])} : {} }
function closed(type, value) { if (!closedValues[type]?.includes(value)) fail('unknown-closed-value', type, String(value)); return value }
function params(value) { const source = object(value, 'WorkflowEffectParams'); return JSON.parse(JSON.stringify(source)) }
function role(value) { const v=object(value,'RoleReference'); const vocabulary=string(v.vocabulary,'RoleReference.vocabulary'); if(vocabulary!=='sys.platform-roles'&&vocabulary!=='tax.roles')fail('unknown-role-vocabulary','RoleReference',vocabulary); return {vocabulary,name:string(v.name,'RoleReference.name')} }

function state(value) { const v=object(value,'WorkflowState'); return {id:required(v,'id','WorkflowState',x=>string(x,'WorkflowState.id')),label:required(v,'label','WorkflowState',x=>readFormsWire('InternationalizedText',x)),kind:required(v,'kind','WorkflowState',x=>closed('WorkflowStateKind',x)),...optional(v,'viewHint',x=>closed('WorkflowViewHint',x))} }
function transition(value) { const v=object(value,'WorkflowTransition'); return {id:string(v.id,'WorkflowTransition.id'),from:string(v.from,'WorkflowTransition.from'),on:string(v.on,'WorkflowTransition.on'),to:string(v.to,'WorkflowTransition.to'),...optional(v,'guard',x=>string(x,'WorkflowTransition.guard')),...optional(v,'requiredRoles',x=>array(x,'WorkflowTransition.requiredRoles',role))} }
function trigger(value) { const v=object(value,'WorkflowTriggerBinding'); return {id:string(v.id,'WorkflowTriggerBinding.id'),kind:closed('WorkflowTriggerKind',v.kind),...optional(v,'eventType',x=>string(x,'WorkflowTriggerBinding.eventType')),...optional(v,'rrule',x=>string(x,'WorkflowTriggerBinding.rrule')),...optional(v,'task',x=>string(x,'WorkflowTriggerBinding.task')),...optional(v,'dependency',x=>string(x,'WorkflowTriggerBinding.dependency'))} }
function actionTarget(value) { const v=object(value,'WorkflowActionBinding.on'); const hasState=Object.hasOwn(v,'state'); const hasTransition=Object.hasOwn(v,'transition'); if (hasState===hasTransition) fail('exclusive-union-mismatch','WorkflowActionBinding.on'); return hasState?{state:string(v.state,'WorkflowActionBinding.on.state')}:{transition:string(v.transition,'WorkflowActionBinding.on.transition')} }
function action(value) { const v=object(value,'WorkflowActionBinding'); return {id:string(v.id,'WorkflowActionBinding.id'),on:actionTarget(v.on),kind:closed('WorkflowActionKind',v.kind),capabilityRef:string(v.capabilityRef,'WorkflowActionBinding.capabilityRef'),classification:closed('ActionClassification',v.classification),...optional(v,'condition',x=>string(x,'WorkflowActionBinding.condition')),...optional(v,'requiredRoles',x=>array(x,'WorkflowActionBinding.requiredRoles',role)),...optional(v,'params',params)} }
function lineage(value) { const v=object(value,'WorkflowDefinitionLineage'); return {parentDefinitionKey:string(v.parentDefinitionKey,'WorkflowDefinitionLineage.parentDefinitionKey'),parentVersion:string(v.parentVersion,'WorkflowDefinitionLineage.parentVersion')} }
function formRef(value) { const v=object(value,'FormDefinitionRef'); return {formId:string(v.formId,'FormDefinitionRef.formId'),version:string(v.version,'FormDefinitionRef.version')} }
function definition(value) { const v=object(value,'WorkflowDefinition'); return {key:string(v.key,'WorkflowDefinition.key'),version:string(v.version,'WorkflowDefinition.version'),status:closed('WorkflowDefinitionStatus',v.status),tenant:string(v.tenant,'WorkflowDefinition.tenant'),owner:readFormsWire('IdentityRef',v.owner),title:readFormsWire('InternationalizedText',v.title),...optional(v,'description',x=>readFormsWire('InternationalizedText',x)),...optional(v,'subjectFormRef',formRef),mutability:closed('WorkflowMutability',v.mutability),initialState:string(v.initialState,'WorkflowDefinition.initialState'),states:array(v.states,'WorkflowDefinition.states',state),transitions:array(v.transitions,'WorkflowDefinition.transitions',transition),triggers:array(v.triggers,'WorkflowDefinition.triggers',trigger),actions:array(v.actions,'WorkflowDefinition.actions',action),guards:array(v.guards,'WorkflowDefinition.guards',x=>readFormsWire('RuleDefinition',x)),...optional(v,'lineage',lineage),createdAt:string(v.createdAt,'WorkflowDefinition.createdAt'),updatedAt:string(v.updatedAt,'WorkflowDefinition.updatedAt')} }

const readers={GuardRef:v=>string(v,'GuardRef'),WorkflowEffectParams:params,WorkflowState:state,WorkflowTransition:transition,WorkflowTriggerBinding:trigger,WorkflowActionBinding:action,WorkflowDefinitionLineage:lineage,FormDefinitionRef:formRef,WorkflowDefinition:definition};
export const workflowWireSurface=Object.freeze({declarations,closedValues});
export function readWorkflowWire(type,value){ if(closedValues[type]) return closed(type,value); const read=readers[type]; if(!read) fail('unknown-type',type); return read(value) }
