using Harborline.Foundation.Assets.Common;

namespace Harborline.Blocks.ActivityTimeline;

/// <summary>Identifies an activity session within a tenant.</summary>
public readonly record struct ActivitySessionId
{
    /// <summary>Creates an identifier; whitespace-only values are rejected.</summary>
    /// <param name="value">The non-empty session identifier.</param>
    public ActivitySessionId(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        Value = value;
    }

    /// <summary>The validated session identifier.</summary>
    public string Value { get; }
    /// <summary>Returns the identifier value.</summary>
    public override string ToString() => Value;
}

/// <summary>A sealed, display-safe identity. It deliberately contains no actor identifier.</summary>
public sealed record ActivityDisplayIdentity
{
    /// <summary>Creates a display-safe identity; whitespace-only names are rejected.</summary>
    /// <param name="displayName">The name safe to show in activity output.</param>
    public ActivityDisplayIdentity(string displayName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(displayName);
        DisplayName = displayName;
    }

    /// <summary>The display-safe name, without an actor identifier.</summary>
    public string DisplayName { get; }
}

/// <summary>Classifies the state or outcome represented by an activity entry.</summary>
public enum ActivityCategory
{
    /// <summary>A proposal is awaiting confirmation.</summary>
    ProposalPending,
    /// <summary>A proposal was confirmed.</summary>
    ProposalConfirmed,
    /// <summary>A proposal was denied.</summary>
    ProposalDenied,
    /// <summary>A capability completed successfully.</summary>
    CapabilityResult,
    /// <summary>A capability failed or returned an error.</summary>
    CapabilityError,
    /// <summary>An activity generated by the system.</summary>
    System
}

/// <summary>Describes an activity action and its optional human-readable detail.</summary>
/// <param name="Action">The action label.</param><param name="Description">Additional detail, or null when absent.</param>
public sealed record ActivityDetail(string Action, string? Description);

/// <summary>An attributed activity entry scoped to a tenant and session.</summary>
/// <param name="Id">The entry identifier.</param>
/// <param name="TenantId">The tenant the entry belongs to.</param>
/// <param name="SessionId">The session the activity happened in.</param>
/// <param name="ProposedBy">The display identity that proposed the activity, or null when none.</param>
/// <param name="ConfirmedBy">The display identity that confirmed the activity, or null when unconfirmed.</param>
/// <param name="Category">What happened: a proposal state, a capability outcome or a system event.</param>
/// <param name="Timestamp">The display timestamp associated with the entry.</param>
/// <param name="Detail">The action and its optional description.</param>
public sealed record ActivityEntry(
    string Id,
    TenantId TenantId,
    ActivitySessionId SessionId,
    ActivityDisplayIdentity? ProposedBy,
    ActivityDisplayIdentity? ConfirmedBy,
    ActivityCategory Category,
    string Timestamp,
    ActivityDetail Detail);

/// <summary>Write-side neutral input. Raw identifiers are accepted here but never copied to returned entries.</summary>
/// <param name="Id">The entry identifier.</param>
/// <param name="TenantId">The tenant the entry belongs to.</param>
/// <param name="SessionId">The session the activity happened in.</param>
/// <param name="ProposedByActorId">The proposing actor identifier, or null.</param>
/// <param name="ConfirmedByActorId">The confirming actor identifier, or null.</param>
/// <param name="Category">What happened: a proposal state, a capability outcome or a system event.</param>
/// <param name="Timestamp">The display timestamp to record.</param>
/// <param name="Detail">The action and its optional description.</param>
public sealed record ActivityEntryDraft(
    string Id,
    TenantId TenantId,
    ActivitySessionId SessionId,
    string? ProposedByActorId,
    string? ConfirmedByActorId,
    ActivityCategory Category,
    string Timestamp,
    ActivityDetail Detail);

/// <summary>Resolves raw actor identifiers into display-safe identities.</summary>
public interface IActivityAttribution
{
    /// <summary>Resolves an actor identifier without exposing it in the returned identity.</summary>
    ActivityDisplayIdentity Resolve(string actorId);
}

/// <summary>Reads activity entries and counts for a tenant/session scope.</summary>
public interface IActivityEntrySource
{
    /// <summary>Returns matching entries in newest-first order.</summary>
    IReadOnlyList<ActivityEntry> Read(TenantId tenantId, ActivitySessionId sessionId);
    /// <summary>Counts entries matching the tenant and session.</summary>
    int Count(TenantId tenantId, ActivitySessionId sessionId);
}

/// <summary>A user-facing notification associated with an activity result.</summary>
public sealed record ActivityNotification(string Id, string Title, string? Body, string Kind, bool Read);

/// <summary>Stores activity entries and notifications in process, newest first.</summary>
public sealed class InMemoryActivityEntrySource : IActivityEntrySource
{
    private readonly IActivityAttribution _attribution;
    private readonly TimeProvider _timeProvider;
    private readonly List<ActivityEntry> _entries = [];
    private readonly List<ActivityNotification> _notifications = [];

    // The pinned addResult read the ambient clock inline; per the platform convention
    // (calendar precedent) time is injected, never ambient — behavior proven identical.
    /// <summary>Creates a source using the supplied attribution resolver and optional clock.</summary>
    public InMemoryActivityEntrySource(IActivityAttribution attribution, TimeProvider? timeProvider = null)
    {
        _attribution = attribution ?? throw new ArgumentNullException(nameof(attribution));
        _timeProvider = timeProvider ?? TimeProvider.System;
    }

    /// <summary>Returns a snapshot of current notifications.</summary>
    public IReadOnlyList<ActivityNotification> Notifications => _notifications.ToArray();

    /// <summary>Prepends an entry after resolving any supplied actor identifiers.</summary>
    public void Append(ActivityEntryDraft draft)
    {
        ArgumentNullException.ThrowIfNull(draft);
        _entries.Insert(0, new ActivityEntry(
            draft.Id, draft.TenantId, draft.SessionId,
            draft.ProposedByActorId is null ? null : _attribution.Resolve(draft.ProposedByActorId),
            draft.ConfirmedByActorId is null ? null : _attribution.Resolve(draft.ConfirmedByActorId),
            draft.Category, draft.Timestamp, draft.Detail));
    }

    /// <summary>Adds a result notification and corresponding success or error activity.</summary>
    public void AddResult(TenantId tenantId, ActivitySessionId sessionId, string id, string title, string? body, bool succeeded)
    {
        var now = _timeProvider.GetLocalNow().ToString("HH:mm");
        _notifications.Insert(0, new($"result:{id}", title, body, "result", false));
        _entries.Insert(0, new($"act:result:{id}", tenantId, sessionId,
            new ActivityDisplayIdentity("System"), null,
            succeeded ? ActivityCategory.CapabilityResult : ActivityCategory.CapabilityError,
            now, new ActivityDetail(title, body)));
    }

    /// <summary>Removes every notification with the specified identifier.</summary>
    public void DismissNotification(string id) => _notifications.RemoveAll(item => item.Id == id);

    /// <summary>Marks all stored notifications as read.</summary>
    public void MarkAllRead()
    {
        for (var index = 0; index < _notifications.Count; index++)
            _notifications[index] = _notifications[index] with { Read = true };
    }

    /// <summary>Returns entries matching the tenant and session in newest-first order.</summary>
    public IReadOnlyList<ActivityEntry> Read(TenantId tenantId, ActivitySessionId sessionId) =>
        _entries.Where(entry => entry.TenantId == tenantId && entry.SessionId == sessionId).ToArray();

    /// <summary>Counts entries matching the tenant and session.</summary>
    public int Count(TenantId tenantId, ActivitySessionId sessionId) =>
        _entries.Count(entry => entry.TenantId == tenantId && entry.SessionId == sessionId);
}
