#!/usr/bin/env node

// Package identity that changes when the package changes (ticket 143).
//
// NuGet resolves by id+version and treats an extracted version as final: "When asked to retrieve a
// package, NuGet first looks in the global-packages folder. If the exact version of the package is
// not there, then NuGet checks all non-HTTP package sources."
// (learn.microsoft.com/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
// So a package repacked every run at a constant 0.0.0-alpha.0 is served from whatever copy landed
// in ~/.nuget/packages first, and today's assembly is never read. The developer sees a compile
// error in a file nobody edited; the gate, which restores into its own --packages folder, sees
// green. Nothing connects the two.
//
// The fix is the version, not the cache: every pack stamps a suffix derived from the content that
// goes into the packages, so a changed tree is a different version, the exact version is not in the
// global folder, and NuGet reads the feed. Two builds of the same tree still share a version --
// that reuse is correct, and it is what keeps the suffix cheap.

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

export const BASE_VERSION = '0.0.0-alpha.0'
export const PROPS_RELATIVE_PATH = 'artifacts/packages/nuget/packed-version.props'

// The same roots prepare-galleries.mjs already declares as the producing inputs of every first-party
// .nupkg. Kept in one list so "what makes a new version" and "what makes a package stale" cannot
// drift apart.
export const PACKAGE_INPUT_ROOTS = [
  'Directory.Build.props',
  'Directory.Packages.props',
  'projections/dotnet',
  'projections/blazor',
]

const excludedDirectories = new Set(['bin', 'obj', 'node_modules', 'dist'])

function filesUnder(path) {
  if (!existsSync(path)) throw new Error(`package version input is missing: ${path}`)
  if (statSync(path).isFile()) return [path]
  return readdirSync(path, { withFileTypes: true })
    .filter(child => !excludedDirectories.has(child.name))
    .flatMap(child => filesUnder(resolve(path, child.name)))
}

// Files that go INTO the packages but live outside the roots above: the root LICENSE that all 24
// csproj files pack with `<None Include="../../../../LICENSE" Pack="true" />`, and anything else a
// project ever marks Pack="true" (an icon, a readme). Enumerated from the pack declarations rather
// than listed by hand, so adding a packed file to a csproj adds it to the hash at the same moment.
function packedNonSourceInputs(projectFiles) {
  const packed = []
  for (const project of projectFiles.filter(path => /\.(cs|fs)proj$|\.props$/.test(path))) {
    const text = readFileSync(project, 'utf8')
    for (const [, include] of text.matchAll(/<(?:None|Content|EmbeddedResource)\s+Include="([^"*?]+)"[^>]*\bPack="true"/g)) {
      const path = resolve(dirname(project), include.replaceAll('\\', '/'))
      if (existsSync(path) && statSync(path).isFile()) packed.push(path)
    }
  }
  return packed
}

/**
 * The version every first-party package is packed at, for the sources currently on disk.
 * Content, not a timestamp and not a counter: the same tree always yields the same version on every
 * machine, and any edit to a packaged source yields a different one.
 */
export function computePackageVersion(root = repositoryRoot) {
  const digest = createHash('sha256')
  const rooted = PACKAGE_INPUT_ROOTS.flatMap(entry => filesUnder(resolve(root, entry)))
  const files = [...new Set([...rooted, ...packedNonSourceInputs(rooted)])]
    .map(path => ({ path, key: relative(root, path).replaceAll('\\', '/') }))
    .sort((left, right) => (left.key < right.key ? -1 : left.key > right.key ? 1 : 0))
  for (const file of files) {
    // Path and content both: a renamed file is a different tree even when the bytes are identical.
    digest.update(file.key)
    digest.update('\0')
    digest.update(createHash('sha256').update(readFileSync(file.path)).digest())
  }
  // SemVer 2.0.0 forbids leading zeros in a NUMERIC pre-release identifier, and an all-digit hash
  // would be exactly that. The 'h' prefix keeps the identifier alphanumeric, so every possible
  // digest produces a version NuGet accepts.
  return `${BASE_VERSION}.h${digest.digest('hex').slice(0, 12)}`
}

/** Writes the version where MSBuild reads it, so a plain `dotnet build` needs no flags. */
export function writePackageVersionProps(root = repositoryRoot, version = computePackageVersion(root)) {
  const path = resolve(root, PROPS_RELATIVE_PATH)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, [
    '<!-- Generated by tooling/package-version.mjs. Not source; artifacts/ is ignored. -->',
    '<Project>',
    '  <PropertyGroup>',
    `    <HarborlinePackedVersion>${version}</HarborlinePackedVersion>`,
    '  </PropertyGroup>',
    '</Project>',
    '',
  ].join('\n'))
  return { path, version }
}

/** The version MSBuild would use right now, or null when nothing has been packed yet. */
export function readPackageVersionProps(root = repositoryRoot) {
  const path = resolve(root, PROPS_RELATIVE_PATH)
  if (!existsSync(path)) return null
  return /<HarborlinePackedVersion>([^<]+)<\/HarborlinePackedVersion>/.exec(readFileSync(path, 'utf8'))?.[1] ?? null
}

if (import.meta.main) {
  process.stdout.write(`${JSON.stringify({ version: computePackageVersion(), packed: readPackageVersionProps() }, null, 2)}\n`)
}
